### ISSUE TITLE
Alternative senders to telegram

### ISSUE THREAD

**Issue by Ramblurr** [flathunters/flathunter#100]
Hi there! Just discovered this project.

Would you accept a PR that adds an additional sender service? I don't use Telegram, so I've added [Pushover](https://pushover.net/) support. I've already got this working locally. But I wanted to ask before making the PR.

I see that the web feature of flathunter makes use of telegram login. I don't think I would add Pushover support to that, though if desired I could.

**Comment by Ramblurr** [comment]
Also, I've written a few crawlers specific to the Austria rental market, I'd be happy to contribute those as well.

**Comment by codders** [comment]
Hey @Ramblurr,

Thanks for your interest, and thanks for asking about the PR. I would say yes - it would be great to have Pushover support. My wish would be that of course the configuration is optional, and that if possible there is some level of test coverage for the code.

Don't worry about Pushover support for the web login. I don't think that's very widely-used, and it is quite Telegram-specific right now.

And of course if you have other crawlers, they would be gratefully received, in a separate pull request.

Many thanks,

Arthur

**Comment by codders** [comment]
Hey @Ramblurr,

Just checking in with you on this one. Did you have a chance to try making a PR? Would you be able to contribute the messaging support or the Austrian crawlers? Would be great if you can. If not I would close this issue.

Thanks!
