### ISSUE TITLE
Is 2captcha required for chrome driver usage?

### ISSUE THREAD

**Issue by mathueb** [flathunters/flathunter#103]
Do I need 2captcha to have immoscout working with selenium/chromedriver?

**Comment by codders** [comment]
Yeah. The filtering on Immoscout is pretty aggressive. I tested just now, and flathunter is working fine locally with 2captcha

**Comment by codders** [comment]
I added a note in the README to try and make this more clear.

**Comment by mathueb** [comment]
thank you for the calrification
