### ISSUE TITLE
Unable to process Ebay expose: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by sbaghdadi** [flathunters/flathunter#104]
While crawling ebay-kleinanzeigen.de I get the following warning:

`[2021/02/23 12:44:21|crawl_ebaykleinanzeigen.py|WARNING ]: Unable to process Ebay expose: 'NoneType' object has no attribute 'text'`

I don't know if this effects the notification in telegram because the message seems fine:

![image](https://user-images.githubusercontent.com/127633/108853072-981e9100-75e6-11eb-9810-c00d5868da16.png)

**Comment by LEQADA** [comment]
I get it too. I think it happens when ebay responds with an unexpected HTML structure. Haven't debugged it though.

**Comment by pcace** [comment]
same here... any idea how to fix this?

**Comment by fkalbe** [comment]
I get the same message. Looks to me like the website layout has changed. If I'm not mistaken, the site also looks slightly different?

I've just started debugging this and the error already seems to be triggered when trying to extract the price in line 63 below, but also for some subsequent data:

https://github.com/flathunters/flathunter/blob/2d84d4b7201a8d1a3b6d8e0cd4ab6689072f08fb/flathunter/crawl_ebaykleinanzeigen.py#L61-L71

My impression is that the 'old' website used the `<strong>` tag for displaying the price, but not longer does. Instead, it seems like they now use `class="aditem-main--middle--price"` for the price. I've just tried replacing this and this seems to at least resolve the error when extracting the price, but the  address extraction also seems to be broken.

**Comment by fkalbe** [comment]
I've just had time to look into this again and I hope the following fix should work. Replace lines 61 to 71 in `flathunter/crawl_ebaykleinanzeigen.py` with the following:

```python        
        for idx, title_el in enumerate(title_elements):
            try:
                price = expose_ids[idx].find(class_="aditem-main--middle--price").text.strip()
                tags = expose_ids[idx].find_all(class_="simpletag tag-small")
                address = expose_ids[idx].find("div", {"class": "aditem-main--top--left"})
                image_element = expose_ids[idx].find("div", {"class": "srpimagebox"})
            except AttributeError as error:
                self.__log__.warning("Unable to process Ebay expose: %s", str(error))
                continue
```

If anyone could confirm this fixes the issue for them I'll submit a PR.

**Comment by sbaghdadi** [comment]
+1 for this fix.

Before:
![Screenshot 2021-03-06 172241](https://user-images.githubusercontent.com/127633/110214135-84571280-7ea3-11eb-9f3c-7957c8f64847.png)

After:
![image](https://user-images.githubusercontent.com/127633/110214138-89b45d00-7ea3-11eb-9470-320b2164b2cf.png)

The Address seems now to be read. Ignore the API-Errors. I never managed to get gmaps api running. Don't know why :D.

Thanks mate!
