### ISSUE TITLE
ERROR: pipenv install => "Warning: Python 3.7 was not found on your system"

### ISSUE THREAD

**Issue by TPunkt** [flathunters/flathunter#106]
Hello,

I'm an absolute python newbie so please have mercy.
Python 3.8.4 is installed on my Win 10 Pro client.

When executing 

`pipenv install`

I get the following errors:

`Warning: Python 3.7 was not found on your system...
Neither 'pyenv' nor 'asdf' could be found to install Python.
You can specify specific versions of Python with:
$ pipenv --python path\to\python`

Thanks a lot for your help.

**Comment by codders** [comment]
I guess the pipenv file is looking for python 3.7. You can try editing the `Pipfile` and changing the Python version requirement at the bottom to 3.8. Or you can install python version 3.7 (instead of 3.8.4).

**Comment by TPunkt** [comment]
Thanks for the quick answer.

I found a pipfile.py but no 3.7 or other verion in it.

**Comment by codders** [comment]
I mean this file: https://github.com/flathunters/flathunter/blob/main/Pipfile

**Comment by TPunkt** [comment]
Thank you very much. 

After changing pipfile 3.7 to 3.8 

`pipenv install
pipenv shell
pip install -e .`

was succesfully run.

Running 

`pytest`

was not.

I think I'd first learn a little bit of python programming before asking again for help.
My hope was using your program is possible without python-knowledge which seems to be required though.

**Comment by fkalbe** [comment]
Running the `pytest` command is not necessary to run the crawler. Put very simply, this command is only meant for developers after they have changed something in the code and want to make sure that everything still works. 

Once you got `pipenv shell` to start successfully, just enter `python flathunt.py` and your crawler should start sending you messages if you got the config right.

**Comment by step21** [comment]
Or you can install pyenv, then pipenv can install the any python version.
