### ISSUE TITLE
data-imgsrc KeyError when crawling ebay-kleinanzeigen 

### ISSUE THREAD

**Issue by richmarv** [flathunters/flathunter#111]
Hi!
I get an error when crawling kleinanzeigen after days with no problem. Did they change something? Here is the error message:

```
Traceback (most recent call last):
  File "flathunt.py", line 89, in <module>
    main()
  File "flathunt.py", line 86, in main
    launch_flat_hunt(config)
  File "flathunt.py", line 46, in launch_flat_hunt
    hunter.hunt_flats()
  File "/home/m/flathunter/flathunter/hunter.py", line 42, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/home/m/flathunter/flathunter/hunter.py", line 22, in crawl_for_exposes
    for searcher in self.config.searchers()
  File "/home/m/flathunter/flathunter/hunter.py", line 23, in <listcomp>
    for url in self.config.get('urls', list())])
  File "/home/m/flathunter/flathunter/abstract_crawler.py", line 136, in crawl
    return self.get_results(url, max_pages)
  File "/home/m/flathunter/flathunter/abstract_crawler.py", line 127, in get_results
    entries = self.extract_data(soup)
  File "/home/m/flathunter/flathunter/crawl_ebaykleinanzeigen.py", line 72, in extract_data
    image = image_element["data-imgsrc"]
  File "/home/m/.pyenv/versions/venv_flathunter/lib/python3.6/site-packages/bs4/element.py", line 992, in __getitem__
    return self.attrs[key]
KeyError: 'data-imgsrc'
```

that is my search-string:
```
https://www.ebay-kleinanzeigen.de/s-wohnung-mieten/mitte/anzeige:angebote/preis::800/c203l3518r5+wohnung_mieten.zimmer_d:2
```

Thanks for looking into it!
Marvin

**Comment by sbaghdadi** [comment]
I can confirm this issue. It seems that ebay-kleinanzeigen change their html-markup on Sunday so that crawling now fails.

**Comment by sbaghdadi** [comment]
As a workaround you can comment the lines 71 - 74 and line 93 as in the screenshot shown below. I don't need the image to be crawled because telegram already pick up the image when showing the the link.

![image](https://user-images.githubusercontent.com/127633/111299543-56ff2700-8650-11eb-843a-9909102603c6.png)
![image](https://user-images.githubusercontent.com/127633/111299578-63837f80-8650-11eb-8b39-17bfc9cd36bd.png)

**Comment by sbaghdadi** [comment]
I took a look in the html-markup. Could somebody confirm that changing line 66 of flathunt/crawl_ebaykleinanzeigen.py to 

`image element = expose ids[idx].find("div", {"class": "galleryimage-element"})`

works?
![image](https://user-images.githubusercontent.com/127633/111301105-1bfdf300-8652-11eb-9480-d6a5fe1cf33a.png)

**Comment by richmarv** [comment]
> I took a look in the html-markup. Could somebody confirm that changing line 66 of flathunt/crawl_ebaykleinanzeigen.py to
> 
> `image element = expose ids[idx].find("div", {"class": "galleryimage-element"})`
> 
> works?

yes it works. thank you!

there are underscores missing in your answer, so it's 

```image_element = expose_ids[idx].find("div", {"class": "galleryimage-element"})```

**Comment by sbaghdadi** [comment]
Yes you're I was missing the underscore. I do a merge request! Thanks for testing.
