### ISSUE TITLE
wg-gesucht crawler generates URLs wiht a double slash, which makes tests fail

### ISSUE THREAD

**Issue by crab-apple** [flathunters/flathunter#117]
I don't know if I'm missing something here. But essentially, it seems that the test test_crawl_wggesucht.py fails on this assertion:

```Python
self.assertTrue(entries[0]['url'].startswith("https://www.wg-gesucht.de/wohnungen"), u"URL should be an apartment link")
```

and the reason it fails is because the urls that the crawler generates contain a double slash after the domain, e.g.:

```'https://www.wg-gesucht.de//wohnungen-in-Berlin-Friedrichshain.8598343.html'```

Apparently when the URL is created (code below), the `href` in the `a` element is assumed to come without a leading slash, but it does in fact come with a leading slash. I guess the wg-gesucht site changed this at some point?

```Python
        base_url = 'https://www.wg-gesucht.de/'
        for row in existing_findings:
            title_row = row.find('h3', {"class": "truncate_title"})
            title = title_row.text.strip()
            url = base_url + title_row.find('a')['href']
```

The functionality still works because the URL with the double slash works just the same, but the tests fail.

If this is confirmed to be an issue, I'd be happy to provide a PR to fix it.

**Comment by codders** [comment]
Yeah. Could be. If you want to change the base_url there not to contain a slash, that would be great - PR very welcome :)

**Comment by crab-apple** [comment]
Would this be ok?
https://github.com/flathunters/flathunter/pull/118

**Comment by codders** [comment]
Yes - excellent work. Thank you so much!

**Comment by crab-apple** [comment]
Awesome, I'll close this then :)
