### ISSUE TITLE
updated flathunter - not working anymore...

### ISSUE THREAD

**Issue by pcace** [flathunters/flathunter#12]
Hey there, i dont know if i am right here, but i have a problem running flathunter. 
I had it up and runnning previousely (version from last october i think). now i tried to reuse it. i updated it via git, and now i get the following error when trying to run it: 

` ./flathunter.py
[2020/06/08 14:42:29|config.py         |INFO    ]: Using config /scripts/flathun                                                                  ter/config.yaml
[2020/06/08 14:42:29|idmaintainer.py   |INFO    ]: already processed: 0
Traceback (most recent call last):
  File "./flathunter.py", line 91, in <module>
    main()
  File "./flathunter.py", line 87, in main
    launch_flat_hunt(config)
  File "./flathunter.py", line 46, in launch_flat_hunt
    hunter.hunt_flats()
  File "/scripts/flathunter/flathunter/hunter.py", line 49, in hunt_flats
    for expose in self.config.get_filter().filter(results):
  File "/scripts/flathunter/flathunter/config.py", line 36, in get_filter
    if "excluded_titles" in filters_config:
TypeError: argument of type 'NoneType' is not iterable
johannes@mail:/scripts/flathunter$
`

is this en error, or did i miss something when installing the dependencies?

Thanks a lot!!!

**Comment by codders** [comment]
Hi pcace,

Thanks for your error report. Are you running the code on master? Can you post your config (with the secrets removed)? It was probably a recent change in the code that broke it.

Arthur

**Comment by pcace** [comment]
Hi,

i started from scratch now but get the same error: 

this is what i did: 

git clone https://github.com/flathunters/flathunter.git
pip3 install -r requirements.txt
python3 flathunter.py

for testing i only changed 2 lines in the config file: 

the search: this is a teststring: 

https://www.immobilienscout24.de/Suche/shape/wohnung-mieten?shape=b3pqX0ltamFwQWJwRWlqQn5kQntyQnh4RGF3TXxTa3JLd3BAZWNKb21Ba2ZEZV9Da19BYWVGZkN1bkdoakJzd0V8d0Zjb0Job0ZhWXh7RHhvQW1iRnx8QXB2VmBoQXZoRXJsQmR1Qw..&price=-1000.0&livingspace=60.0-&enteredFrom=result_list&viewMode=MAP#/?boundingBox=52.395369%2C13.22581%2C52.595983%2C13.61026

and then the telegram token wich looks like this (it was always working...)

telegram:
    bot_token: XXXXXXXXXXXXXXXXXXX
    receiver_ids:
        - -XXXXXXX

It may be my beginnerlevel pythin knowledge, but maybe you can still help me with this?

Cheers and thank you!

**Comment by codders** [comment]
Hi again,

I fixed this is the latest pull request (#13). Please clone again from master (or git pull to get the latest) and retry. Let me know if you have any other trouble!

Thanks,

Arthur

**Comment by pcace** [comment]
Impressive! ;) 

works perfect! Thank you!!!
