### ISSUE TITLE
Install Flathunter via Docker

### ISSUE THREAD

**Issue by pcace** [flathunters/flathunter#121]
Hi there, 

i would be really happy if someone could help me with an install via Docker (i am completely new to docker)
What i did: 
git clone flathunter
then 
docker build .
and then 
docker run container id

but where am i supposed to put the config to?
i have put it to /opt/flathunter/config.yaml, but when i start the container, i get this: 

docker run 4d5bdc629481
usage: flathunt.py [-h] [--config CONFIG]
flathunt.py: error: argument --config/-c: can't open '/config/config.yaml': [Errno 2] No such file or directory: '/config/config.yaml'

What does it mean with /config/config.yaml? (i even tried to mkdir /config/ and did put the config in there, but that does not change anything... 

its probably very easy, but i just dont yet understand this docker stuff^^

Thanks a lot!!

**Comment by Tareqox** [comment]
Hi just remove the config parameter from flathunter.py within the Dockerfile. This did work for me

**Comment by pcace** [comment]
Hi, 

thanks a lot, i got a little bit further, but still have a problem with the config file (wich was working before on an other install)

```
[2021/06/10 09:57:56|config.py         |INFO    ]: Using config /app/config.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'YOUR_CHROME_DRIVER_PATH'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flathunt.py", line 89, in <module>
    main()
  File "flathunt.py", line 68, in main
    config = Config(config_handle.name)
  File "/app/flathunter/config.py", line 29, in __init__
    self.__searchers__ = [CrawlImmobilienscout(self),
  File "/app/flathunter/crawl_immobilienscout.py", line 43, in __init__
    self.driver = self.configure_driver(self.driver_executable_path, self.driver_arguments)
  File "/app/flathunter/abstract_crawler.py", line 51, in configure_driver
    driver = webdriver.Chrome(executable_path=driver_path, options=chrome_options)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'YOUR_CHROME_DRIVER_PATH' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

What would be the appropriate location for the crome driver?

Thanks a lot!

**Comment by milou12345** [comment]
It says it right in your error log:
 `FileNotFoundError: [Errno 2] No such file or directory: 'YOUR_CHROME_DRIVER_PATH'`
You did  not configure your yaml before building the docker container

**Comment by codders** [comment]
@pcace Did this resolve the issue for you?

**Comment by matiya** [comment]
If you don't need the google maps api, you can't comment that part out and it should work.

**Comment by alexanderroidl** [comment]
@pcace What's the state of your problem? Where you able to fix it? 😀

**Comment by alexanderroidl** [comment]
@pcace [Updates concerning Docker](https://github.com/flathunters/flathunter/pull/189) were released today. Please take a look at the new [Docker section inside the README](https://github.com/flathunters/flathunter#docker) and feel free to open another issue if your problem still persists.
