### ISSUE TITLE
Pause until captcha solved manually / by chrome extension

### ISSUE THREAD

**Issue by herbertgroff** [flathunters/flathunter#134]
Hi!

First of all: Thanks for this great project!

Since solving chaptchas via 2captcha API using headless doesnt work at the moment, I'm trying to make it work by solving the captcha manually or using the 2captcha chrome extension (which works fine). Only problem is, the bot crashes once the captcha page appears. Is there any chance to skip the captcha part and make it just wait until the result page appears?

Thanks a lot!

**Comment by BananaMinion** [comment]
Hey, i got this already.
As soon as i have time i will add a PR - right now i have hard coded debug messages with my ID in it :D

**Comment by intxcc** [comment]
Hi @BananaMinion 

geecaptcha solving will work if you just add this to block the captcha from showing

```
driver.sendDevToolsCommand('Network.setBlockedURLs', { urls: ['https://api.geetest.com/get.*'] });
driver.sendDevToolsCommand('Network.enable', {});
```

Then you can easily grab the 3 geetest parameters and get 2captcha to solve the challenge ;)

**Comment by BananaMinion** [comment]
Why dont u add a PR then?

**Comment by intxcc** [comment]
Currently working on it :)

**Comment by codders** [comment]
Merged this - thanks so much @intxcc for the fix!

**Comment by dnberlin** [comment]
Awesome @intxcc !

**Comment by intxcc** [comment]
You're welcome!
