### ISSUE TITLE
How to search in multiple districts for ebay-kleinanzeigen?

### ISSUE THREAD

**Issue by iwasherefirst2** [flathunters/flathunter#143]
First of all thank you for this application, its amazing and works really good.

However, I have a question if I can search for multiple districts for ebay-kleinanzeigen.de As far as I understood this website, its
not possible to search in multiple districts by one url. The district is part of the url, like `https://www.ebay-kleinanzeigen.de/s-wohnung-mieten/steglitz/c203l3414+wohnung_mieten.qm_d:90,+wohnung_mieten.zimmer_d:4` or `https://www.ebay-kleinanzeigen.de/s-wohnung-mieten/steglitz/c203l3414+wohnung_mieten.qm_d:90,+wohnung_mieten.zimmer_d:4`. 

So I guess in order to search for multiple districts in ebay-kleinanzeigen, one needs to add multiple urls.
But this may conflict with the comment in your config from your sleepingtime: 
```

# Note that Ebay will (temporarily) block your IP if you
# poll too often - don't lower this below 600 seconds if you
# are crawling Ebay.

```

Does it mean that ebay-kleinanzeigen gonna block me if I have sleeping_time 600 and two urls (because it would be equivalent to having one url and sleeping_time 300, right)? Do I need to increase sleeping_time by 600 for each additional url? If ebay-kleinanzeigen temporarily blocks me, will this show in the output (when starting flathunter.py from cli). ?

**Comment by clemwo** [comment]
I'm also curious. Have you tried multiple URLs?  
I just managed to get the bot running yesterday and I simply put in multiple URLs for ebay-kleinanzeigen and so far I haven't seen any errors in the logs.

**Comment by iwasherefirst2** [comment]
I tried multiple urls but reduced it back to one. I noticed that there were new results that did not pop up in my inbox. I think there is currently no log when the site gets blocked.

**Comment by step21** [comment]
I just use the url for the whole city, as it's an ebay limitation, and as there are not that many results once you adjust for exclusions, I think that is accepatable. If you want verbose logs, you can enable debug logging in the code. This might also log blocked sites better, but not super sure.

**Comment by iwasherefirst2** [comment]
@step21 do you also use geo-targeting? I mean in Berlin there are a lot of districts, I guess you get spammed with new messages without destrict restricitons?

**Comment by step21** [comment]
@iwasherefirst2 on ebay kleinanzeigen, there are not that many, especially when you filter out WBS, Tausch or similar things (I have a few other exclusions, but if those make sense depends on what you are looking for I gues). (protected housing and flat exchange) On everything else I use geo-targeting of course.

**Comment by iwasherefirst2** [comment]
@step21 so you use Google API Keys for distance matrix calculation? How much does this costs?

**Comment by step21** [comment]
No. That's not worth it for me. I meant with other websites, I use more restrictions based on area.

**Comment by iwasherefirst2** [comment]
Okay, thanks for the hint
