### ISSUE TITLE
Why is chrome-web-driver required?

### ISSUE THREAD

**Issue by iwasherefirst2** [flathunters/flathunter#146]
To run 2captcha you seem to require chrome-web-driver. Why is that? According to the 2captcha API I could not find any mentioning reagradin this https://github.com/2captcha/2captcha-python

**Comment by codders** [comment]
That's probably leftover from when we were solving with recaptcha (which does need the webdriver). Does it run okay if you drop the dependency?

**Comment by iwasherefirst2** [comment]
When I drop it, I get on each request a recaptcha, if I keep it, only one out of 12 requests requires a recaptcha. Not sure if I make something wrong when just using curl, but it looks it has impact. However, there seems to be this bug that if recaptcha takes too long, this chrome-web-driver will just die https://github.com/flathunters/flathunter/issues/113
