### ISSUE TITLE
Can't install on Ubuntu 21.10

### ISSUE THREAD

**Issue by achimcc** [flathunters/flathunter#156]
Hello, I try to install flathunter on Ubuntu 21.10, every time after `pipenv install`, I end up with:

> Creating a virtualenv for this project…
> Using /usr/local/bin/python3.7m (3.7.5) to create virtualenv…
> ⠋created virtual environment CPython3.7.5.final.0-64 in 158ms
>   creator CPython3Posix(dest=/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo, clear=False, no_vcs_ignore=False, global=False)
>   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/flathunter/.local/share/virtualenv)
>     added seed packages: pip==20.3.4, pkg_resources==0.0.0, setuptools==44.1.1, wheel==0.34.2
>   activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
> 
> Virtualenv location: /home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo
> Pipfile.lock (1925e8) out of date, updating to (ee42c9)…
> Locking [dev-packages] dependencies…
> Locking [packages] dependencies…
> 
> Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
>   You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
> Could not find a version that matches beautif
>

**Comment by codders** [comment]
Can you try removing 'pkg_resources==0.0.0' from your Pipfile? I guess that doesn't belong there.

**Comment by alexanderroidl** [comment]
@achimcc Does your problem still persist? Otherwise I would like to close this issue.
