### ISSUE TITLE
abstract_crawler.py - Solve geetest → Captcha never gets solved

### ISSUE THREAD

**Issue by markuswestphal** [flathunters/flathunter#158]
Hej community! ☀️

I've been using the project for 2 weeks now and i'm blown away by its utility. Thank you all for your work 🙏🏼

Issue:
Starting last monday, march 8th, i've not been getting any more results for Immoscout24.
The abstract_crawler tries to solve a geetest captcha (every time on when executing) and renders a `Captcha was not sovable` after multiple `CAPTCHA_NOT_READY` responses. 

I tried to investigate and debug but my python is yet limited and i don't know how to solve that. 
Anyone having the same issue? Any recommendations on what to try?

The URL in my config: https://www.immobilienscout24.de/Suche/de/berlin/berlin/wohnung-mieten?haspromotion=false&numberofrooms=2.0-&price=-650.0&livingspace=40.0-&exclusioncriteria=swapflat&pricetype=rentpermonth&geocodes=110000000801,110000000901,110000000307,110000000703,110000000902,110000001101,110000001112,110000000101,110000000201,110000001103,110000000102,110000000202,110000000301,110000000104,110000000302,110000000105,110000000106,110000000701&enteredFrom=result_list

<img width="908" alt="Screenshot 2022-03-10 at 09 23 39" src="https://user-images.githubusercontent.com/15379315/157619932-ff5fedc0-106f-4a51-ae20-7249712c8075.png">

**Comment by markuswestphal** [comment]
After having a brief chat with the guys from 2Captcha, the geetest request render a valid promise again. Seems like the issue was on their side to me. I'm closing this issue for now.

**Comment by iwasherefirst2** [comment]
Thank you for contacting! Although this is great news, the script should not crash if gee tests fails I think, but thow an waring log and continue is the better option

**Comment by iwasherefirst2** [comment]
There is nothing wrong with receiving a "Captcha was not solvable" message. 2captcha won't charge you when this happens and its a documented result in their API: https://2captcha.com/2captcha-api

![grafik](https://user-images.githubusercontent.com/1765602/162125337-11063262-c8b7-4523-8955-dd484d083626.png)

And it was already taken care of that here: https://github.com/flathunters/flathunter/blob/main/flathunter/abstract_crawler.py#L178

So, it still happens frequently and it will so in the future and its still all good :)
