### ISSUE TITLE
immobilienscout24.de postings are not working for me

### ISSUE THREAD

**Issue by Alvarny** [flathunters/flathunter#169]
immobilienscout24.de has a bot protection in place that renders the app for the site almost unuseable for me. Other sites work fine!
The scrawler can't pick up the new listings because of it, at least most of the time. 
Can we figure something out to circumvent it?

**Comment by codders** [comment]
Did you install and configure chromedriver? Are you using the imagetyperz
support?

Arthur

Alvarny ***@***.***> schrieb am Mi., 11. Mai 2022, 12:18:

**Comment by Alvarny** [comment]
Uff, closed. I overlooked this part in the config. Thanks for heads-up!
