### ISSUE TITLE
How to add a new url?

### ISSUE THREAD

**Issue by iwasherefirst2** [flathunters/flathunter#171]
I would like to write another crawler for https://inberlinwohnen.de/ do I just need to add a new file crawler_inberlinwohnen.py and import crawler? Or do I need to register that file anywhere?

**Comment by step21** [comment]
Did you actually try anything or look at the code? I have not tested this, but at the very least you would need to add it to config.py, like the other crawlers.

**Comment by mordax7** [comment]
Here you can find a commit where someone added an Italian real state website https://github.com/flathunters/flathunter/commit/95e3774eb7404f7795da78f98d715926eac5939c

So in short, yes, you can copy most of the code from another crawler and adjust it to [inberlinwohnen.de/](https://inberlinwohnen.de/.
