### ISSUE TITLE
wg-gesucht uses captcha

### ISSUE THREAD

**Issue by mordax7** [flathunters/flathunter#175]
Here is part of the response body when catching the captcha:
```html
<form name="checkform" method="post" action="https://www.wg-gesucht.de/cuba.html">\n
    <div style="margin-left:5%;">\n <input type="hidden" name="step" value="2">\n <input type="hidden"
                                                                                         name="page"
                                                                                         value="/wohnungen-in-Munchen.90.2.1.0.html">\n
        <div class="g-recaptcha" data-sitekey="6LciNA4TAAAAAHQZGcdTxO_KIskhDWevImHFo60D"></div>
        \n <br/>\n <input type="submit" class="btn btn-primary mb5" value="Absenden">\n
    </div>
    \n
</form>
```

I hit it probably because I spammed it with requests. Could not reproduce it when openening in personal browser.

TODO:
* Use Selenium to open wg-gesucht
* See if you can reproduce the issue there
* If reproducable, use the captcha solving services to solve it

**Comment by codders** [comment]
I haven't seen this and it wasn't reported by anyone else. For me, crawling seems to work without captcha solving for wggesucht. Marking this as closed for now - feel free to reopen it if you find a way to reproduce the issue.
