### ISSUE TITLE
How to add a new user?

### ISSUE THREAD

**Issue by Velvelyn** [flathunters/flathunter#177]
When I want to add a new user, the following problem occurs:

/opt$ sudo -u flathunter pip install --user pipenv
WARNING: The directory '/home/flathunter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pipenv in /usr/lib/python3/dist-packages (11.9.0)
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Keine Berechtigung: '/home/flathunter'
Check the permissions.

Does anyone have an idea?

**Comment by codders** [comment]
Hi @Velvelyn ,

This looks like a permissions problem on your linux machine. The error message mentions "If executing pip with sudo, you may want sudo's -H flag.". Have you tried the -H flag, e.g.:

sudo -u flathunter -H pip install --user pipenv

**Comment by alexanderroidl** [comment]
@Velvelyn Did codder's suggestion work for you?
