### ISSUE TITLE
GeeTest captcha unsolvable via 2captcha

### ISSUE THREAD

**Issue by marcelmindemann** [flathunters/flathunter#197]
Hi,
I am running `flathunter` on the latest commit [5a5b78c](https://github.com/flathunters/flathunter/commit/5a5b78c892696f55771d696540492b2496a02aba) in Docker.
I am using the 2Captcha integration to crawl immoscout24, which has worked fine until yesterday. Sometime during last night, the GeeTest captchas from immoscout24 became unsolveable, leading to log messages like:

```
flathunter    | [2022/08/14 12:45:07|twocaptcha_solver.py    |INFO    ]: Captcha is not ready yet, waiting...
flathunter    | [2022/08/14 12:45:12|twocaptcha_solver.py    |DEBUG   ]: Got response from 2captcha/res: CAPCHA_NOT_READY
flathunter    | [2022/08/14 12:45:12|twocaptcha_solver.py    |INFO    ]: Captcha is not ready yet, waiting...
flathunter    | [2022/08/14 12:45:18|twocaptcha_solver.py    |DEBUG   ]: Got response from 2captcha/res: ERROR_CAPTCHA_UNSOLVABLE
flathunter    | [2022/08/14 12:45:18|twocaptcha_solver.py    |INFO    ]: The captcha was unsolvable.
flathunter    | [2022/08/14 12:45:20|_common.py              |ERROR   ]: Giving up resolve_geetest(...) after 3 tries (flathunter.captcha.captcha_solver.CaptchaUnsolvableError)
flathunter    | [2022/08/14 12:45:20|hunter.py               |INFO    ]: Error while scraping url https://www.immobilienscout24.de/Suche/shape/wohnung-mieten?shape=a2...U.&enteredFrom=result_list#/: the captcha was unsolvable
```

I am unsure if this is a problem with GeeTest and 2Captcha, or something about the 2Captcha API changed, so I'm reporting it here aswell. Feel free to close this isssue if you are sure it is an upstream problem.

**Comment by AkioNuernberger** [comment]
Getting the same error

**Comment by marcelmindemann** [comment]
Since this error has solved itself, I assume it was a temporary problem on 2Captcha's side. I will close this issue.
