### ISSUE TITLE
CrawlImmobilienscout crashing

### ISSUE THREAD

**Issue by thyzerle** [flathunters/flathunter#199]
On running the flathunter.service I get this error:

> Aug 20 17:03:12 tsegger systemd[1]: Started Flathunter Python Script.
> Aug 20 17:03:16 tsegger flathunter[19722]: [2022/08/20 17:03:16|config.py               |INFO    ]: Using config /opt/flathunter/config.yaml
> Aug 20 17:03:16 tsegger flathunter[19722]: [2022/08/20 17:03:16|abstract_crawler.py     |INFO    ]: Initializing Chrome WebDriver for crawler "CrawlImmobilienscout"...
> Aug 20 17:03:17 tsegger flathunter[19722]: Traceback (most recent call last):
> Aug 20 17:03:17 tsegger flathunter[19722]:   File "flathunt.py", line 105, in <module>
> Aug 20 17:03:17 tsegger flathunter[19722]:     main()
> Aug 20 17:03:17 tsegger flathunter[19722]:   File "flathunt.py", line 76, in main
> Aug 20 17:03:17 tsegger flathunter[19722]:     config.init_searchers()
> Aug 20 17:03:17 tsegger flathunter[19722]:   File "/opt/flathunter/flathunter/config.py", line 44, in init_searchers
> Aug 20 17:03:17 tsegger flathunter[19722]:     CrawlImmobilienscout(self),
> Aug 20 17:03:17 tsegger flathunter[19722]:   File "/opt/flathunter/flathunter/crawl_immobilienscout.py", line 38, in __init__
> Aug 20 17:03:17 tsegger flathunter[19722]:     self.driver = self.configure_driver(driver_arguments)
> Aug 20 17:03:17 tsegger flathunter[19722]:   File "/opt/flathunter/flathunter/abstract_crawler.py", line 62, in configure_driver
> Aug 20 17:03:17 tsegger flathunter[19722]:     options=chrome_options
> Aug 20 17:03:17 tsegger flathunter[19722]:   File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 72, in __init__
> Aug 20 17:03:17 tsegger flathunter[19722]:     service_log_path, service, keep_alive)
> Aug 20 17:03:17 tsegger flathunter[19722]:   File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 97, in __init__
> Aug 20 17:03:17 tsegger flathunter[19722]:     options=options)
> Aug 20 17:03:17 tsegger flathunter[19722]:   File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 277, in __init__
> Aug 20 17:03:17 tsegger flathunter[19722]:     self.start_session(capabilities, browser_profile)
> Aug 20 17:03:17 tsegger flathunter[19722]:   File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 370, in start_session
> Aug 20 17:03:17 tsegger flathunter[19722]:     response = self.execute(Command.NEW_SESSION, parameters)
> Aug 20 17:03:17 tsegger flathunter[19722]:   File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
> Aug 20 17:03:17 tsegger flathunter[19722]:     self.error_handler.check_response(response)
> Aug 20 17:03:17 tsegger flathunter[19722]:   File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
> Aug 20 17:03:17 tsegger flathunter[19722]:     raise exception_class(message, screen, stacktrace)
> Aug 20 17:03:17 tsegger flathunter[19722]: selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
> Aug 20 17:03:17 tsegger flathunter[19722]:   (unknown error: DevToolsActivePort file doesn't exist)
> Aug 20 17:03:17 tsegger flathunter[19722]:   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
> Aug 20 17:03:17 tsegger flathunter[19722]: Stacktrace:
> Aug 20 17:03:17 tsegger flathunter[19722]: #0 0x55d6d37a92d3 <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #1 0x55d6d35b33fa <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #2 0x55d6d35d87da <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #3 0x55d6d35d3ae4 <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #4 0x55d6d360f1f3 <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #5 0x55d6d3608fe3 <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #6 0x55d6d35dee33 <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #7 0x55d6d35e0015 <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #8 0x55d6d37f53fd <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #9 0x55d6d37f899c <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #10 0x55d6d37dc39e <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #11 0x55d6d37f95d3 <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #12 0x55d6d37d028f <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #13 0x55d6d3817728 <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #14 0x55d6d38178d2 <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #15 0x55d6d383199f <unknown>
> Aug 20 17:03:17 tsegger flathunter[19722]: #16 0x7fb6fc844fa3 <unknown>
> Aug 20 17:03:17 tsegger systemd[1]: flathunter.service: Main process exited, code=exited, status=1/FAILURE
> Aug 20 17:03:17 tsegger systemd[1]: flathunter.service: Failed with result 'exit-code'.

When I remove the `CrawlImmobilienscout(self)` from config.py everything works perfectly

**Comment by alexanderroidl** [comment]
Hi @TimS-Official, can you try adding the following arguments for ```--no-sandbox``` and/or ```--remote-debugging-port=9222``` to your main configuration ```config.yaml``` at ```captcha/driver_arguments```?

**Comment by TimS-Official** [comment]
When only adding `--no-sandbox` the error is the same
When adding both the `DevToolsActivePort file doesn't exist` is replaced by `chrome not reachable`

**Comment by TimS-Official** [comment]
I tried refollowing the installation guide. And set `verbose: true`
Now the error is different:

> Aug 21 17:42:05 tsegger systemd[1]: Started Flathunter Python Script.
> Aug 21 17:42:09 tsegger flathunter[15266]: [2022/08/21 17:42:09|config.py               |INFO    ]: Using config /opt/flathunter/config.yaml
> Aug 21 17:42:09 tsegger flathunter[15266]: [2022/08/21 17:42:09|flathunt.py             |DEBUG   ]: Settings from config: <flathunter.config.Config object at 0x7f0a9100b0b8>
> Aug 21 17:42:09 tsegger flathunter[15266]: [2022/08/21 17:42:09|abstract_crawler.py     |INFO    ]: Initializing Chrome WebDriver for crawler "CrawlImmobilienscout"...
> Aug 21 17:42:09 tsegger flathunter[15266]: [2022/08/21 17:42:09|<WebDriverManager>      |DEBUG   ]: ====== WebDriver manager ======
> Aug 21 17:42:09 tsegger flathunter[15266]: [2022/08/21 17:42:09|<WebDriverManager>      |DEBUG   ]: Get LATEST chromedriver version for google-chrome None
> Aug 21 17:42:09 tsegger flathunter[15266]: [2022/08/21 17:42:09|<WebDriverManager>      |DEBUG   ]: Driver [/home/flathunter/.wdm/drivers/chromedriver/linux64/104.0.5112/chromedriver] found in cache
> Aug 21 17:42:09 tsegger flathunter[15266]: Traceback (most recent call last):
> Aug 21 17:42:09 tsegger flathunter[15266]:   File "flathunt.py", line 105, in <module>
> Aug 21 17:42:09 tsegger flathunter[15266]:     main()
> Aug 21 17:42:09 tsegger flathunter[15266]:   File "flathunt.py", line 76, in main
> Aug 21 17:42:09 tsegger flathunter[15266]:     config.init_searchers()
> Aug 21 17:42:09 tsegger flathunter[15266]:   File "/opt/flathunter/flathunter/config.py", line 44, in init_searchers
> Aug 21 17:42:09 tsegger flathunter[15266]:     CrawlImmobilienscout(self),
> Aug 21 17:42:09 tsegger flathunter[15266]:   File "/opt/flathunter/flathunter/crawl_immobilienscout.py", line 38, in __init__
> Aug 21 17:42:09 tsegger flathunter[15266]:     self.driver = self.configure_driver(driver_arguments)
> Aug 21 17:42:09 tsegger flathunter[15266]:   File "/opt/flathunter/flathunter/abstract_crawler.py", line 62, in configure_driver
> Aug 21 17:42:09 tsegger flathunter[15266]:     options=chrome_options
> Aug 21 17:42:09 tsegger flathunter[15266]:   File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 72, in __init__
> Aug 21 17:42:09 tsegger flathunter[15266]:     service_log_path, service, keep_alive)
> Aug 21 17:42:09 tsegger flathunter[15266]:   File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 97, in __init__
> Aug 21 17:42:09 tsegger flathunter[15266]:     options=options)
> Aug 21 17:42:09 tsegger flathunter[15266]:   File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 277, in __init__
> Aug 21 17:42:09 tsegger flathunter[15266]:     self.start_session(capabilities, browser_profile)
> Aug 21 17:42:09 tsegger flathunter[15266]:   File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 370, in start_session
> Aug 21 17:42:09 tsegger flathunter[15266]:     response = self.execute(Command.NEW_SESSION, parameters)
> Aug 21 17:42:09 tsegger flathunter[15266]:   File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
> Aug 21 17:42:09 tsegger flathunter[15266]:     self.error_handler.check_response(response)
> Aug 21 17:42:09 tsegger flathunter[15266]:   File "/home/flathunter/.local/share/virtualenvs/flathunter--s35lxKo/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
> Aug 21 17:42:09 tsegger flathunter[15266]:     raise exception_class(message, screen, stacktrace)
> Aug 21 17:42:09 tsegger flathunter[15266]: selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
> Aug 21 17:42:09 tsegger flathunter[15266]: Stacktrace:
> Aug 21 17:42:09 tsegger flathunter[15266]: #0 0x55b24afd7403 <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #1 0x55b24addd778 <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #2 0x55b24adff916 <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #3 0x55b24adfd12b <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #4 0x55b24ae3883a <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #5 0x55b24ae328f3 <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #6 0x55b24ae080d8 <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #7 0x55b24ae09205 <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #8 0x55b24b01ee3d <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #9 0x55b24b021db6 <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #10 0x55b24b00813e <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #11 0x55b24b0229b5 <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #12 0x55b24affc970 <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #13 0x55b24b03f228 <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #14 0x55b24b03f3bf <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #15 0x55b24b059abe <unknown>
> Aug 21 17:42:09 tsegger flathunter[15266]: #16 0x7f9c77812fa3 <unknown>
> Aug 21 17:42:09 tsegger systemd[1]: flathunter.service: Main process exited, code=exited, status=1/FAILURE
> Aug 21 17:42:09 tsegger systemd[1]: flathunter.service: Failed with result 'exit-code'.

But again, when I remove `CrawlImmobilienscout(self)` from config.py everything works.

I guess the difference is that with the new setup I didnt install chromedriver / google-chrome

**Comment by codders** [comment]
Do you have an exact version match between your webdriver version and your chrome version? I see the error `cannot find Chrome binary` - where is chrome located on the target system?

**Comment by TimS-Official** [comment]
I followed the first part of this tutorial: https://yizeng.me/2014/04/20/install-chromedriver-and-phantomjs-on-linux-mint/

Therefore I installed the newest version which was something with 105.x

**Comment by squilaSC** [comment]
Running in docker I needed to add these two arguments for it to run.

`- "--headless"`
`- "--no-sandbox"`

**Comment by abuchmueller** [comment]
@squilaSC thanks, this makes the docker image run but I experienced a crash.
After rebooting it seems to work now, though.

``` 
22/08/23 22:12:55|config.py               |INFO    ]: Using config /config.yaml
[2022/08/23 22:12:55|flathunt.py             |DEBUG   ]: Settings from config: <flathunter.config.Config object at 0x7fada60c5bd0>
[2022/08/23 22:12:55|abstract_crawler.py     |INFO    ]: Initializing Chrome WebDriver for crawler "CrawlImmobilienscout"...

[2022/08/23 22:12:55|<WebDriverManager>      |DEBUG   ]: ====== WebDriver manager ======
[2022/08/23 22:12:55|<WebDriverManager>      |DEBUG   ]: Get LATEST chromedriver version for google-chrome 104.0.5112
[2022/08/23 22:12:55|<WebDriverManager>      |DEBUG   ]: There is no [linux64] chromedriver for browser 104.0.5112 in cache
[2022/08/23 22:12:55|<WebDriverManager>      |DEBUG   ]: About to download new driver from https://chromedriver.storage.googleapis.com/104.0.5112.79/chromedriver_linux64.zip
[2022/08/23 22:12:56|<WebDriverManager>      |DEBUG   ]: Driver has been saved in cache [/root/.wdm/drivers/chromedriver/linux64/104.0.5112]
[2022/08/23 22:12:57|crawl_immobilienscout.py|DEBUG   ]: Got search URL https://www.immobilienscout24.de/Suche/de/XXXX
[2022/08/23 22:13:00|twocaptcha_solver.py    |INFO    ]: Trying to solve geetest.
[2022/08/23 22:13:00|twocaptcha_solver.py    |DEBUG   ]: Got response from 2captcha/in: OK|71318916888
[2022/08/23 22:13:00|twocaptcha_solver.py    |DEBUG   ]: Got response from 2captcha/res: CAPCHA_NOT_READY
[2022/08/23 22:13:00|twocaptcha_solver.py    |INFO    ]: Captcha is not ready yet, waiting...
[2022/08/23 22:13:05|twocaptcha_solver.py    |DEBUG   ]: Got response from 2captcha/res: CAPCHA_NOT_READY
[2022/08/23 22:13:05|twocaptcha_solver.py    |INFO    ]: Captcha is not ready yet, waiting...
[2022/08/23 22:13:10|twocaptcha_solver.py    |DEBUG   ]: Got response from 2captcha/res: CAPCHA_NOT_READY
[2022/08/23 22:13:10|twocaptcha_solver.py    |INFO    ]: Captcha is not ready yet, waiting...
[2022/08/23 22:13:15|twocaptcha_solver.py    |DEBUG   ]: Got response from 2captcha/res: CAPCHA_NOT_READY
[2022/08/23 22:13:15|twocaptcha_solver.py    |INFO    ]: Captcha is not ready yet, waiting...
[2022/08/23 22:13:20|twocaptcha_solver.py    |DEBUG   ]: Got response from 2captcha/res: CAPCHA_NOT_READY
[2022/08/23 22:13:20|twocaptcha_solver.py    |INFO    ]: Captcha is not ready yet, waiting...
[2022/08/23 22:13:25|twocaptcha_solver.py    |DEBUG   ]: Got response from 2captcha/res: CAPCHA_NOT_READY
[2022/08/23 22:13:25|twocaptcha_solver.py    |INFO    ]: Captcha is not ready yet, waiting...
[2022/08/23 22:13:30|twocaptcha_solver.py    |DEBUG   ]: Got response from 2captcha/res: CAPCHA_NOT_READY
[2022/08/23 22:13:30|twocaptcha_solver.py    |INFO    ]: Captcha is not ready yet, waiting...
[2022/08/23 22:13:35|twocaptcha_solver.py    |DEBUG   ]: Got response from 2captcha/res: CAPCHA_NOT_READY
[2022/08/23 22:13:35|twocaptcha_solver.py    |INFO    ]: Captcha is not ready yet, waiting...
[2022/08/23 22:13:41|twocaptcha_solver.py    |DEBUG   ]: Got response from 2captcha/res: CAPCHA_NOT_READY
[2022/08/23 22:13:41|twocaptcha_solver.py    |INFO    ]: Captcha is not ready yet, waiting...
[2022/08/23 22:13:46|twocaptcha_solver.py    |DEBUG   ]: Got response from 2captcha/res: OK|{"geetest_challenge":"013d7f12095c46075d2bed1d1f2e1736","geetest_validate":"xxx","geetest_seccode":"xxx|jordan"}
Traceback (most recent call last):
  File "flathunt.py", line 105, in <module>
    main()
  File "flathunt.py", line 101, in main
    launch_flat_hunt(config, heartbeat)
  File "flathunt.py", line 31, in launch_flat_hunt
    hunter.hunt_flats()
  File "/usr/src/app/flathunter/hunter.py", line 54, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/usr/src/app/flathunter/hunter.py", line 34, in crawl_for_exposes
    for searcher in self.config.searchers()
  File "/usr/src/app/flathunter/hunter.py", line 35, in <listcomp>
    for url in self.config.get('urls', [])])
  File "/usr/src/app/flathunter/hunter.py", line 25, in try_crawl
    return searcher.crawl(url, max_pages)
  File "/usr/src/app/flathunter/abstract_crawler.py", line 158, in crawl
    return self.get_results(url, max_pages)
  File "/usr/src/app/flathunter/crawl_immobilienscout.py", line 55, in get_results
    soup = self.get_page(search_url, self.driver, page_no)
  File "/usr/src/app/flathunter/crawl_immobilienscout.py", line 128, in get_page
    afterlogin_string=self.afterlogin_string
  File "/usr/src/app/flathunter/abstract_crawler.py", line 93, in get_soup_from_url
    return BeautifulSoup(driver.page_source, 'html.parser')
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 541, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=104.0.5112.101)
Stacktrace:
#0 0x55f5fd451403 <unknown>
#1 0x55f5fd25764b <unknown>
#2 0x55f5fd24475a <unknown>
#3 0x55f5fd24365b <unknown>
#4 0x55f5fd243c1c <unknown>
#5 0x55f5fd24fc3f <unknown>
#6 0x55f5fd2507a2 <unknown>
#7 0x55f5fd25edad <unknown>
#8 0x55f5fd262c6a <unknown>
#9 0x55f5fd244046 <unknown>
#10 0x55f5fd25e951 <unknown>
#11 0x55f5fd2bfb53 <unknown>
#12 0x55f5fd2ac8f3 <unknown>
#13 0x55f5fd2820d8 <unknown>
#14 0x55f5fd283205 <unknown>
#15 0x55f5fd498e3d <unknown>
#16 0x55f5fd49bdb6 <unknown>
#17 0x55f5fd48213e <unknown>
#18 0x55f5fd49c9b5 <unknown>
#19 0x55f5fd476970 <unknown>
#20 0x55f5fd4b9228 <unknown>
#21 0x55f5fd4b93bf <unknown>
#22 0x55f5fd4d3abe <unknown>
#23 0x7f19cccf6ea7 <unknown>
```

**Comment by TimS-Official** [comment]
Can confirm @abuchmueller 's experience.
Switched to docker using @squilaSC 's driver arguments and get the same Errors very irregularly (sometimes after 30min sometimes after 3 hours)

Thanks to dockers restart unless stopped it just restarts the process and I can actually use it

**Comment by alexanderroidl** [comment]
> Edit3:
> Runs for 24+ hours without crashing now. Seems to work :)

 🎉
