### ISSUE TITLE
Linux installtion error: 

### ISSUE THREAD

**Issue by Briare0s** [flathunters/flathunter#200]
Hi learning noob here, trying to install on Ubuntu 20.04

At step `$ sudo -u flathunter pip install --user pipenv` I get the following error:

`WARNING: The directory '/home/flathunter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.`

When using the -H flag I still get the error: `ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/home/flathunter' Check the permissions.`

My permissions for /opt/flathunter: `drwxr-xr-x  6 flathunter flathunter 4096 aug 20 21:32 flathunter`

How to proceed?

**Comment by alexanderroidl** [comment]
Hi @Briare0s, thank you for using Flathunter! Could you please try the suggested solution of [this issue](https://github.com/flathunters/flathunter/issues/177)?

**Comment by codders** [comment]
@Briare0s what are the permissions on `/home/flathunter/.cache`?

**Comment by cdonat2** [comment]
@codders Got the same problem setting up flathunter on Kubunu 20.04.

Using `sudo -u flathunter -H pip install --user pipenv` didn't solve the problem. Also, the repository is placed in /opt/flathunter as described in the linux installation guide, so I am not sure where /home/flathunter/.cache should exist.

**Comment by alexanderroidl** [comment]
@cdonat2 The ```.cache``` directory does not have to exist, but it should be possible for your process (owned by your user) to create it. That is not the case due to wrong permissions.

You have posted permissions of your ```flathunter``` directory. Does this concern ```/opt/flathunter``` or ```/home/flathunter```?

Please send the output for both directory's permissions.

**Comment by cdonat2** [comment]
The permissions concern `/opt/flathunter`. I looked up the other directory and even though the user and group for flathunter exist, no `/home/flathunter` was created.

Setting up the project as described in the first part of the installation guide worked as intended though.

**Comment by codders** [comment]
Great - thanks for the additional information!

@Briare0s does this resolve your issue too?

**Comment by Briare0s** [comment]
Excuse for the delay, I was away for a bit. Will work on it this weekend and get back to you. Thanks for all the replies so far. :)

**Comment by Briare0s** [comment]
Let me formulate my steps to learn from, as I'm sure there is a more efficient way.

`sudo su - flathunter` to temporary change to user flathunter
`[cannot access '/home/flathunter': No such file or directory](su: warning: cannot change directory to /home/flathunter: No such file or directory)` confirms the directory doesn't exist.
Now when I exit and `sudo useradd -m flathunter`, it tells me `useradd: user 'flathunter' already exists`.

Do I need to remove the user first for the `-m` switch to work?

**Comment by codders** [comment]
Yeah. I guess you will need a `userdel -r` to delete things before the
useradd command will work.

Briareos ***@***.***> schrieb am Di., 6. Sept. 2022, 18:12:

**Comment by Briare0s** [comment]
That did the trick, thanks for the assistance everybody! (and if anybody is looking for a Dutch flatmate, feel free to reach out. ;))
