### ISSUE TITLE
Immobilienscout24 with 2captcha failing

### ISSUE THREAD

**Issue by wuzawuza** [flathunters/flathunter#219]
First thank for the implementation. 
My deployment did run flawless for weeks, now it stopped working. 

My Url: https://www.immobilienscout24.de/Suche/radius/wohnung-mieten?centerofsearchaddress=M%C3%BCnchen;;;;;Maxvorstadt&numberofrooms=4.0-&geocoordinates=48.14847;11.5641;5.0&sorting=2

When I pdb into the crawler I see that the soup content is still the captcha page. 
I was not able to fix it myself - I would suspect that the captcha feedback is not properly looped back and then the redirect to the result page is not triggerd.

<img width="677" alt="Capture" src="https://user-images.githubusercontent.com/113626152/190459720-7feea31c-8e44-4e41-976d-716b41a132cb.PNG">

Any ideas?

**Comment by wuzawuza** [comment]
I did further digging:        

` result = re.findall(r"initGeetest\({(.*?)}", driver.page_source, re.DOTALL)
geetest = re.findall("gt: \"(.*?)\"", result[0])[0]
challenge = re.findall("challenge: \"(.*?)\"", result[0])[0]
`

This part seems to still do the job - all regex results look right

`
            script = (f'solvedCaptcha({{geetest_challenge: "{captcha_response.challenge}",'
                      f'geetest_seccode: "{captcha_response.sec_code}",'
                      f'geetest_validate: "{captcha_response.validate}",'
                      f'data: "{data}"}});')
            driver.execute_script(script)
`

This one seems to be not OK anymore. I struggle to debug since I dont come to the captcha page on my local machine. Any hints welcome!

**Comment by codders** [comment]
@wuzawuza Are you still seeing this issue? I've not been able to reproduce this on my own deployments,

**Comment by lleschinski** [comment]
@wuzawuza 
I had the same problem until yesterday. 

My bot was using a version which was a few months old, which I think might be the same in your case.
After I updated my flathunter with the latest version everything works fine again. 

Maybe updating solves the issue for you as well.

**Comment by wuzawuza** [comment]
yes - I was on an old version. Now it works fine.
I actually was on the wrong HEAD (still prior to this fork....) so git pull was not giving much ....
Thanks to everyone!

If anyone is experiencing:

`selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:34237
from chrome not reachable`

for it helped to:

- install chromedriver in /opt/chrome/chromedriver
- add to the config.yaml:

`       driver_path: /opt/chrome/chromedriver
       driver_arguments:
         - "--headless"`
