### ISSUE TITLE
Issue - Initializing Chrome WebDriver for crawler "CrawlImmobilienscout"

### ISSUE THREAD

**Issue by Tydnl** [flathunters/flathunter#227]
Hi guys, 
I'm facing a problem when it comes to crawling Immoscout24. 
Everything in the config is usually set up correctly but it seems something with the chromedriver is broken. 

Here you can see the full issue that I'm facing within the terminal:

<img width="1276" alt="Bildschirmfoto 2022-09-21 um 16 47 00" src="https://user-images.githubusercontent.com/111451410/191538365-44978467-e91e-4660-b98a-6b5a589bd340.png">

Looking forward to get some help here.

Thank you in advance!

**Comment by codders** [comment]
Hi @Tydnl ,

Was that issue persistent - do you still have the problem? Looking quickly at google, this looks like it might be a temporary certificate configuration problem on the ImmoScout side, or some other problem with your connection.

**Comment by Tydnl** [comment]
HI @codders,

Thank you for your response.

Unfortunately, I'm still facing the exact same problem as described above. 
I've tried different connections and its the same everywhere. 
Once I kick ImmoScout out of the config everything works properly.

**Comment by codders** [comment]
@Tydnl Can you try the steps here:
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/122

It seems like other users have a similar issue, and it could be related to your python installation.

**Comment by Tydnl** [comment]
@codders Thanks for letting me know. Unfortunately, the solution in your mentioned thread solved the problem on linux, I guess but I'm running the script via the terminal on my mac which is still not working so far. I'm searching further.

**Comment by Tydnl** [comment]
Problem solved: OSX had no certificates to validate SSL connections

For all of you facing the same problem, have a look at the following thread which helped me to solve the issue:
https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

**Comment by codders** [comment]
Awesome - thanks so much for the reseach!
