### ISSUE TITLE
flathunter.service: Failed to locate executable /home/flathunter/.local/bin/pipenv: Permission denied

### ISSUE THREAD

**Issue by clemwo** [flathunters/flathunter#228]
Hey there,
Im using a google cloud vm instance with CentOS 9 and get the following error when Im starting the flathunter service:

```
× flathunter.service - Flathunter Python Script
     Loaded: loaded (/usr/lib/systemd/system/flathunter.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2022-09-22 18:23:11 UTC; 2s ago
   Duration: 10ms
    Process: 217734 ExecStart=/home/flathunter/.local/bin/pipenv run python flathunt.py (code=exited, status=203/EXEC)
   Main PID: 217734 (code=exited, status=203/EXEC)
        CPU: 5ms

Sep 22 18:23:11 umi-flathunter-bot systemd[1]: Started Flathunter Python Script.
Sep 22 18:23:11 umi-flathunter-bot systemd[217734]: flathunter.service: Failed to locate executable /home/flathunter/.local/bin/pipenv: Permission denied
Sep 22 18:23:11 umi-flathunter-bot systemd[217734]: flathunter.service: Failed at step EXEC spawning /home/flathunter/.local/bin/pipenv: Permission denied
Sep 22 18:23:11 umi-flathunter-bot systemd[1]: flathunter.service: Main process exited, code=exited, status=203/EXEC
Sep 22 18:23:11 umi-flathunter-bot systemd[1]: flathunter.service: Failed with result 'exit-code'.
```

I just followed the installation instructions for Linux but had to add a few sudos here and there and change the permission of the folder.

When I go and check the permissions in ``/home/flathunter/.local/bin/`` with ``ls -l`` I get the following:

```
-rwxrwxrwx. 1 flathunter flathunter 203 Sep 22 17:04 pipenv
-rwxrwxrwx. 1 flathunter flathunter 214 Sep 22 17:04 pipenv-resolver
-rwxrwxrwx. 1 flathunter flathunter 238 Sep 22 17:04 virtualenv
-rwxrwxrwx. 1 flathunter flathunter 214 Sep 22 17:04 virtualenv-clone
```

To me that doesnt really look wrong. 

Can anyone help out here?  

Is it possible that I created the virtualenv as root or something? [Read this on here](https://stackoverflow.com/questions/19471972/how-to-avoid-permission-denied-when-using-pip-with-virtualenv)   

Any help is greatly appreciated

**Comment by codders** [comment]
Can you paste what the service file looks like? It could be a systemd permissions thing on the service, but I don't really know my way around systemd so well.

**Comment by codders** [comment]
Closing this because of lack of information.
