### ISSUE TITLE
Getting index error from immobilienscout with 2Captcha

### ISSUE THREAD

**Issue by krush-pak** [flathunters/flathunter#260]
Hi all,

I'm getting an index error when running flathunter.py for immobilienscout:

`[2022/11/13 18:12:13|crawl_immobilienscout.py|ERROR   ]: Index error occurred`

Is this a known issue? Would be great to get help on that.

**Comment by codders** [comment]
Hi @krush-pak ,

To crawl immoscout, you need google-chrome installed and 2captcha setup. Are you using a 2captcha-enabled setup?

**Comment by krush-pak** [comment]
Hi @codders, thanks for the quick response. I triple-checked the 2captcha setup and found the problem! It's working now
