### ISSUE TITLE
Supported websites

### ISSUE THREAD

**Issue by patrickvacek** [flathunters/flathunter#27]
The [config file sample](https://github.com/flathunters/flathunter/blob/main/config.yaml.dist#L13) says that only immoscout and wg-gesucht are supported. However, the README claims immowelt and ebay Kleinanzeigen work as well. Is that just an oversight, or am I missing something?

Thanks for sharing a great tool!

**Comment by codders** [comment]
The sample config seems not to have been updated when new crawlers have been added. Immowelt and Kleinanzeigen are definitely working too.

**Comment by patrickvacek** [comment]
Small thing, I know, but shall I make a PR?

**Comment by codders** [comment]
Yes - please do!
