### ISSUE TITLE
Python 3.8 in README but 3.7 in Dockerfile

### ISSUE THREAD

**Issue by bvolkmer** [flathunters/flathunter#275]
In README, it is stated that the requirement is python3.8+. But the Dockerfile fetches the python3.7 base image.

**Comment by codders** [comment]
Ah. Interesting :) I stopped testing against 3.7 in CI - we only run tests against 3.8, 3.9 and 3.10. It would make sense to bump the Dockerfile - do you want to open a PR?

**Comment by codders** [comment]
This is closed with #280. Thanks for the PR!
