### ISSUE TITLE
Problem with Setup

### ISSUE THREAD

**Issue by Ocdjs** [flathunters/flathunter#285]
Hi
I have a problem setting up the flathunter. This is the message I got: 

'PS C:\Users\user\github\flathunter-main\flathunter-main python3 flathunt.py
Traceback (most recent call last):
File "C:\Users\user\github\flathunter-main\flathunter-main\flathunt.py", line 13, in 
 from flathunter.hunter import Hunter
 File "C:\Users\user\github\flathunter-main\flathunter-main\flathunter\hunter.py", line 4, in 
import requests
ModuleNotFoundError: No module named 'requests''

Unfortunately I do not understand a lot regarding python, so I do not know what my mistake is.

Would be very glad if you could help me out!

**Comment by codders** [comment]
Hi @Ocdjs ,

It looks like the 'requests' module is missing. You need to follow the installation instructions and install 'pipenv', and use 'pipenv' to install the python modules used by flathunter.

**Comment by codders** [comment]
Hi @Ocdjs ,

Did that work for you? Can I close this issue?

**Comment by codders** [comment]
Closing this - lack of feedback
