### ISSUE TITLE
Issue with docker script 

### ISSUE THREAD

**Issue by domdiak** [flathunters/flathunter#286]
I am getting an error when trying to run a command for docker image build : 

`docker build -t flathunter-job -f Dockerfile.gcloud.job .` from Google Cloud Run Deployment section

The last script `chrome_driver_install.py` is failing: 

```
 => ERROR [10/10] RUN python chrome_driver_install.py                                                                                                           0.6s
------
 > [10/10] RUN python chrome_driver_install.py:
#14 0.538 Traceback (most recent call last):
#14 0.538   File "chrome_driver_install.py", line 5, in <module>
#14 0.540     from webdriver_manager.chrome import ChromeDriverManager
#14 0.542 ModuleNotFoundError: No module named 'webdriver_manager'
```

Am I missing something obvious / how should I proceed?

**Comment by codders** [comment]
Is your `requirements.txt` up to date? `requirements.txt` has been removed from version control - you will need to manually update in by doing a `pip freeze | grep -v flathunter > requirements.txt` from your `pipenv shell`.

**Comment by domdiak** [comment]
Amazing, worked! Thanks so much for such a rapid response!
