### ISSUE TITLE
Issue with launching ImmoScout scraper

### ISSUE THREAD

**Issue by friedrichtroescher** [flathunters/flathunter#311]
Hey, i have this issue - i can't figure out what causes it though. The Config seems to be set okay. Does anyone have any insight on what might cause this?

> (flathunter_immoscout) bash-3.2$ python flathunt.py
> [2023/02/12 17:31:59|config.py               |INFO    ]: Using config path /Users/friedrichtroscher/bin/flathunter_immoscout/config.yaml
> [2023/02/12 17:31:59|chrome_wrapper.py       |INFO    ]: Initializing Chrome WebDriver for crawler...
> [2023/02/12 17:32:01|patcher.py              |INFO    ]: patching driver executable /Users/friedrichtroscher/Library/Application Support/undetected_chromedriver/undetected_chromedriver
> Traceback (most recent call last):
>   File "/Users/friedrichtroscher/bin/flathunter_immoscout/flathunt.py", line 109, in <module>
>     main()
>   File "/Users/friedrichtroscher/bin/flathunter_immoscout/flathunt.py", line 75, in main
>     config.init_searchers()
>   File "/Users/friedrichtroscher/bin/flathunter_immoscout/flathunter/config.py", line 98, in init_searchers
>     CrawlImmobilienscout(self),
>   File "/Users/friedrichtroscher/bin/flathunter_immoscout/flathunter/crawl_immobilienscout.py", line 40, in __init__
>     self.driver = get_chrome_driver(driver_arguments)
>   File "/Users/friedrichtroscher/bin/flathunter_immoscout/flathunter/chrome_wrapper.py", line 44, in get_chrome_driver
>     driver = uc.Chrome(version_main=chrome_version, options=chrome_options) # pylint: disable=no-member
>   File "/Users/friedrichtroscher/.local/share/virtualenvs/flathunter_immoscout-FtMFl5Tx/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 411, in __init__
>     browser = subprocess.Popen(
>   File "/Users/friedrichtroscher/opt/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/Users/friedrichtroscher/opt/anaconda3/lib/python3.9/subprocess.py", line 1696, in _execute_child
>     and os.path.dirname(executable)
>   File "/Users/friedrichtroscher/opt/anaconda3/lib/python3.9/posixpath.py", line 152, in dirname
>     p = os.fspath(p)
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> [2023/02/12 17:32:01|__init__.py             |INFO    ]: ensuring close

**Comment by codders** [comment]
I guess this might also be associated with the issue in #310. You can either rollback to a previous version of the software, or wait until there's another update from the undetected-chromedriver project.

**Comment by codders** [comment]
Just merged in #313, which bumps `undetected-chromedriver` up a version. Maybe try again and see if that's better?

**Comment by friedrichtroescher** [comment]
This works for me now too, thanks.
