### ISSUE TITLE
Pipenv install not working: Hashes not matching

### ISSUE THREAD

**Issue by stelo-lg** [flathunters/flathunter#314]
Hello,

I am trying to run it on my Raspberry Pi 3 with DietPi. I've created the flathunter user and installed pip/pipenv. 

If I run pipenv install it fails with the following problem: 

> [pipenv.exceptions.InstallError]: ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
> 
> [pipenv.exceptions.InstallError]:     apprise==1.2.1 from https://www.piwheels.org/simple/apprise/apprise-1.2.1-py2.py3-none-any.whl#sha256=864723a261053b25fbea76842ecd0cfd91e89c7303f75f233931513e7282f364 (from -r /tmp/pipenv-37bxrk49-requirements/pipenv-a4rqyfqu-hashed-reqs.txt (line 1)):
> [pipenv.exceptions.InstallError]:         Expected sha256 679fb5d6232ec7748eef308bda9fe0f0707fa5e48eab247bfde83c3a024a21d1
> [pipenv.exceptions.InstallError]:         Expected     or 67e0c227eecee260000980dbbf8ba1e5eebdbe494f4730808297c9e645c03579
> [pipenv.exceptions.InstallError]:              Got        864723a261053b25fbea76842ecd0cfd91e89c7303f75f233931513e7282f364

I have also run `pipenv lock --pre` like suggested in another issue. However, it did not help. 

I also deleted the Pipfile.lock file and run it again, but that did not help either. 

What am I missing there? 

EDIT: It seems to help if a manually add the hashed in the Pipfile.lock that are prompted in the error message as above. But is there any way to do that automatically? 

Thank you for your help!

**Comment by stelo-lg** [comment]
I have changed the source in the Pipfile to 

> https;//www.piwheels.hostedpi.com/simple

 and run `pipenv install --skip-lock`. Looks like this worked out for me.

**Comment by codders** [comment]
Hi @stelo-lg ,

The lockfile that we ship is build on an Linux machine - it makes sense (and is a good security feature) that the checksums don't match if you're installing for a different architecture. I'll update the documentation to reflect your experience. Thanks for the investigation / feedback!
