### ISSUE TITLE
Feature: Expose env variable to enable filters with Google Cloud Deployment

### ISSUE THREAD

**Issue by infctr** [flathunters/flathunter#318]
Hello! First of all thank you for setting up this awesome project!

Would it be possible to add an env variable to allow filtering by titles in Google Cloud Deployment? 
I can see there's `filters.excluded_titles` available in yaml config, however yaml config is ignored with gcloud build, isn't it?

**Comment by codders** [comment]
Hi @infctr ,

Thanks! Happy that the work is appreciated :) Actually, the `gcloud build` will bundle your `config.yaml` and include that in the deployment - you should be able to go ahead and the set `excluded_titles` in the YAML config and have it work. But if for whatever reason this doesn't work for you, let me know and I'll add it to the Docker variables in the coming days.

**Comment by infctr** [comment]
Hi, @codders 

Thank you for getting back on this so quickly!
Actually my `config.yaml` is configured like this 
```
filters:
  excluded_titles:
    - 'wg'
    - 'zwischenmiete'
    - 'swap'
    - 'kurzzeitmiete'
    - 'sublet'
    - 'tausch'
```
However it's not working. It's supposed to be case-insensitive but it's not https://github.com/flathunters/flathunter/blob/main/flathunter/filter.py#L121
Am I missing something?

**Comment by codders** [comment]
That looks okay. Have you tried it without the quotes around the filter words? Does it work okay for you running locally?

We definitely have had problems with excluded titles in the past, and it's not a feature I personally test with. But looking at the code, it looks like it ought to work and ought to be case insensitive.

If removing the quotes doesn't help, let me know and I will take a look later this week. Thanks!

**Comment by infctr** [comment]
@codders Removing quotes from `excluded_titles` seems to be working as expected! Thank you!

I think we can close this issue

**Comment by codders** [comment]
Thanks for the feedback :)

**Comment by infctr** [comment]
@codders I think I need to bring this up again, but it doesn't seem like filters are working after all. I've added a debug logger to `TitleFilter` [class in the code](https://github.com/flathunters/flathunter/blob/main/flathunter/filter.py#L119) to figure out whether config values are picked up properly, but it's doesn't get logged at all. Unfortunately, this is as far as my debugging with python goes. Are filters working as expected?

**Comment by codders** [comment]
Hi @infctr ,

I'm not normally using the title filter for my configs, but I've had no other reports that it's broken. The filter will only be configured if you have the 'excluded_titles' item in your 'filters' config - if that's missing, the TitleFilter will never be invoked. So it could be a formatting problem with your YAML file. If you are adding logging, you could also add a 'print(self.filters)' at the end of 'read_config' in the 'FilterBuilder' class - that would tell you what filters the code has managed to parse from your config file.

**Comment by infctr** [comment]
@codders Thank you for the heads up!

I've added these lines to `read_config`

```
logger.debug('Filter debug: %s', self.filters)
logger.debug('Filter debug: %s', filters_config["excluded_titles"])
```

Logs well running locally in docker, however fails with an error on Google cloud job with 
```
File "cloud_job.py", line 23, in <module> hunter.hunt_flats() File "/usr/src/app/flathunter/web_hunter.py", line 16, in hunt_flats .read_config(self.config) \ File "/usr/src/app/flathunter/filter.py", line 184, in read_config logger.debug('Filter debug: %s', filters_config["excluded_titles"]) UnboundLocalError: local variable 'filters_config' referenced before assignment
```

So it looks like `config.yaml` is actually ignored in Google cloud jobs. 
Would it be possible to pass filter params with env variables perhaps?

**Comment by codders** [comment]
@infctr I've just merged in code that should add support for the `FLATHUNTER_FILTER_EXCLUDED_TITLES` environment variable - you need to supply a semi-colon separated list of titles:

```
FLATHUNTER_FILTER_EXCLUDED_TITLES=tausch;stadt mitte;wg
```

If that doesn't work, please reopen the issue.

**Comment by infctr** [comment]
@codders Thank you for the update! 

I can see there were some additional deps update, so not sure whether this is caused by the latest update or one of the previous ones. Any idea on what's causing this error on start? 

`Traceback (most recent call last): File "cloud_job.py", line 23, in <module> hunter.hunt_flats() File "/usr/src/app/flathunter/web_hunter.py", line 31, in hunt_flats for expose in processor_chain.process(self.crawl_for_exposes(max_pages=max_pages)): File "/usr/src/app/flathunter/hunter.py", line 36, in crawl_for_exposes for searcher in self.config.searchers() File "/usr/src/app/flathunter/hunter.py", line 37, in <listcomp> for url in self.config.target_urls()]) File "/usr/src/app/flathunter/hunter.py", line 27, in try_crawl return searcher.crawl(url, max_pages) File "/usr/src/app/flathunter/abstract_crawler.py", line 150, in crawl return self.get_results(url, max_pages) File "/usr/src/app/flathunter/crawl_immobilienscout.py", line 89, in get_results soup = self.get_page(search_url, self.get_driver(), page_no) File "/usr/src/app/flathunter/crawl_immobilienscout.py", line 64, in get_driver self.driver = get_chrome_driver(driver_arguments) File "/usr/src/app/flathunter/chrome_wrapper.py", line 47, in get_chrome_driver driver = uc.Chrome(version_main=chrome_version, options=chrome_options) # pylint: disable=no-member File "/usr/local/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 439, in __init__ service=service, # needed or the service will be re-created File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 90, in __init__ keep_alive, File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 114, in __init__ options=options, File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__ self.start_session(capabilities, browser_profile) File "/usr/local/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 694, in start_session capabilities, browser_profile File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session response = self.execute(Command.NEW_SESSION, parameters) File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute self.error_handler.check_response(response) File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:47165`

**Comment by codders** [comment]
Hi @infctr ,

I just tried with a fresh checkout on my machine (clone the latest, run the config wizard), and it seems to work without any problems. I'm running on Linux with Python 3.11. You seem to be using Python 3.7 - that's heading to end-of-life in a couple of months. I don't know if a newer python version would help you, but it could be worth a shot.

The only (maybe) suspicious change that I made was here to the default arguments for 'headless' mode: https://github.com/flathunters/flathunter/blame/a956a3cdb3f7e19352135af8f94294b26f730c75/flathunter/config.py#L376 . If you set the arguments manually in your config file, this shouldn't affect you.

I don't / can't test on mac, so if there's an issue there it will be hard for me to debug.

**Comment by infctr** [comment]
@codders I see, thank you. That's because `Dockerfile.gcloud.job` references `python:3.7` as a source image. Will have to use a newer version.

**Comment by codders** [comment]
Hey @infctr ,

Thanks for the nudge! I'll take a look

**Comment by infctr** [comment]
@codders But will creating `requirements.txt` actually work since `Dockerfile.gcloud.job` creates its own with `RUN pip install -r requirements.txt`?

**Comment by codders** [comment]
That does the install - that won't create a new requirements file

**Comment by infctr** [comment]
So I was able to make this work with the following

```diff
diff --git a/.gcloudignore b/.gcloudignore
index 9d8971e..ea0f582 100644
--- a/.gcloudignore
+++ b/.gcloudignore
@@ -18,7 +18,6 @@ __pycache__/
 # Ignored by the build system
 /setup.cfg
 /Pipfile
-/Pipfile.lock

 # Don't upload the database
 processed_ids.db
diff --git a/Dockerfile.gcloud.job b/Dockerfile.gcloud.job
index adad097..2d89931 100644
--- a/Dockerfile.gcloud.job
+++ b/Dockerfile.gcloud.job
@@ -1,4 +1,4 @@
-FROM python:3.7
+FROM python:3.10

 ENV PYTHONDONTWRITEBYTECODE 1
 ENV PYTHONUNBUFFERED 1
@@ -10,6 +10,10 @@ RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable
 RUN apt-get -y update
 RUN apt-get install -y google-chrome-stable

+# Upgrade pip, install pipenv
+RUN pip install --upgrade pip
+RUN pip install pipenv
+
 # Copy files
 WORKDIR /usr/src/app
 COPY . .
@@ -18,6 +22,7 @@ COPY . .
 RUN pip install --upgrade pip

 # Generate requirements.txt and install dependencies from there
+RUN pipenv requirements > requirements.txt
 RUN pip install -r requirements.txt

 RUN python chrome_driver_install.py
```

**Comment by infctr** [comment]
Also IS24 crawling started working with my Google Cloud deployment, as it turns out `Dockerfile.gcloud.job` image was out of date
