### ISSUE TITLE
Any plans to add support for Immoscout plus members?

### ISSUE THREAD

**Issue by denizs** [flathunters/flathunter#324]
Basically what the title says :)

**Comment by codders** [comment]
What would that support look like? Are there listings that only plus-members see? Or do you want some of the extra infos from plus membership in the Telegram messages?

It would in principle be possible to make the crawler log in to Immoscout, but since Immoscout offers no API, it would be a lot of scraping and fighting with bot detection. Plus someone would have to sponsor us an immoscout premium membership :)

What are your use-cases?

**Comment by denizs** [comment]
Sorry, maybe I should've provided a tad more of context. :sweat: 

> Are there listings that only plus-members see?

Exactly this - immo scout plus members have access to listings for a predefined number of days before "regular" members see them.

Frankly, I didn't look into how i24's handling auth-n client side, but maybe one can work around that by supplying something :tm:  within the `configuration.yaml`. From the top of my head, I reckon this will only work until you - the real person behind the account - logs out with a different device or something, but for my purposes, this would already be a neat 80/20 solution.

**Comment by codders** [comment]
Ah. Yeah. That explains a lot. I had a premium membership for a bit, but that was a while back - I forgot what was in there. Also, screw that company - more of a Pest on the Immobilienmarkt than the bots are :)

The project doesn't make any money, so integrating premium features would basically mean they stay untested / unmaintained. I think there would be something genuinely emancipatory in leaking the premium listings to a shared public instance (see https://flathunter.codders.io ), and making a commitment to maintain and pay for that, but I don't have the time or the spare cash right now.

If you want to make a PR for logged-in immoscout scraping, I would merge it, but like I say it won't be tested, so the feature will probably rot as soon as you found your flat :)

**Comment by denizs** [comment]
>  Also, screw that company - more of a Pest on the Immobilienmarkt than the bots are :)

Amen! I mean, who offers a premium mebership that costs the same money for 3 _and_ 12 months. Even deutsche bahn with their Probe BahnCard had the decency of offering it at a quarter of the yearly fee, which still feels like 1980s German business practices. :upside_down_face: 

Hmhm - got it and I do understand.

> I think there would be something genuinely emancipatory in leaking the premium listings to a shared public instance (see https://flathunter.codders.io/ ), and making a commitment to maintain and pay for that, but I don't have the time or the spare cash right now.

I'm just shittalking here, but one could make this the best troll ever and offer on demand immo scout plus for a fixed price per conversation to offset the plus membership :joy:  

Alrighty! I'll think about it and pray that I have some spare time on the week ends to put my hands on the keys. 

In the meantime - thanks a bunch for that project :pray: I'm just getting started with looking for a new flat (in Cologne) and was really thankful I didn't have to start fro scratch here :)

In case you're ever interested in auto booking urban sports club classes when someone withdraws, hmu :grimacing:
