### ISSUE TITLE
No telegram bot token error

### ISSUE THREAD

**Issue by tandomayo** [flathunters/flathunter#334]
I am following the format given in config.yaml.dist

 telegram:
   bot_token: XXXX
   notify_with_images: true
   receiver_ids:
       - XXXX

But it keeps giving me an error saying "No Telegram bot token configured. Starting like this would be pointless..."

Is the bot-token in the wrong format??

**Comment by codders** [comment]
Hi @tandomayo ,

I'm not sure if the formatting you used is a 1-to-1 match - spacing / indentation is important in Yaml. The config should look like:

```
telegram:
    bot_token: 112xxxx
    receiver_ids:
        - 15xxxx
```

The latest version of software includes a `config_wizard.py` script to help generate the config file - maybe that's also helpful. But if this doesn't work and the wizard doesn't help, it might be a programming error in the latest code. Let me know!

**Comment by tandomayo** [comment]
Ah yes, that fixed it. But now I have a new problem. 

_AttributeError: 'Heartbeat' object has no attribute '_Heartbeat__notifier'. Did you mean: '_Heartbeat__interval'?_

**Comment by codders** [comment]
Yeah. If you don't have a 'notifiers' section, you'll get that message (again, the config_wizard is your friend here):

```
notifiers:
  - telegram
```

**Comment by codders** [comment]
(but I admit that's a stupid error message for that condition - if you leave the ticket open, I'll make a real fix for this so that the AttributeError goes away and the program notifies you about the missing config section)

**Comment by tandomayo** [comment]
Ah! And voila......its working :)

(and least I think it is)
