### ISSUE TITLE
Problem to get Flathunter running

### ISSUE THREAD

**Issue by PlanetDyna** [flathunters/flathunter#34]
Unfortunately I have a problem to get Flathunter up and running. When I run "pytest" I get the following error message:

======================================================================== ERRORS =========================================================================
_________________________________________________________ ERROR collecting test/test_config.py __________________________________________________________
ImportError while importing test module '/home/planetdyna/test/test_config.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/test_config.py:5: in <module>
    from flathunter.config import Config
E   ImportError: No module named flathunter.config
_________________________________________________ ERROR collecting test/test_crawl_ebaykleinanzeigen.py _________________________________________________
ImportError while importing test module '/home/planetdyna/test/test_crawl_ebaykleinanzeigen.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/test_crawl_ebaykleinanzeigen.py:2: in <module>
    from flathunter.crawl_ebaykleinanzeigen import CrawlEbayKleinanzeigen
E   ImportError: No module named flathunter.crawl_ebaykleinanzeigen
__________________________________________________ ERROR collecting test/test_crawl_immobilienscout.py __________________________________________________
ImportError while importing test module '/home/planetdyna/test/test_crawl_immobilienscout.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/test_crawl_immobilienscout.py:3: in <module>
    from flathunter.crawl_immobilienscout import CrawlImmobilienscout
E   ImportError: No module named flathunter.crawl_immobilienscout
_____________________________________________________ ERROR collecting test/test_crawl_immowelt.py ______________________________________________________
ImportError while importing test module '/home/planetdyna/test/test_crawl_immowelt.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/test_crawl_immowelt.py:3: in <module>
    from flathunter.crawl_immowelt import CrawlImmowelt
E   ImportError: No module named flathunter.crawl_immowelt
_____________________________________________________ ERROR collecting test/test_crawl_wggesucht.py _____________________________________________________
ImportError while importing test module '/home/planetdyna/test/test_crawl_wggesucht.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/test_crawl_wggesucht.py:3: in <module>
    from flathunter.crawl_wggesucht import CrawlWgGesucht
E   ImportError: No module named flathunter.crawl_wggesucht
________________________________________________ ERROR collecting test/test_gmaps_duration_processor.py _________________________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
E     File "/home/planetdyna/test/test_gmaps_duration_processor.py", line 28
E   SyntaxError: Non-ASCII character '\xd0' in file /home/planetdyna/test/test_gmaps_duration_processor.py on line 29, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
________________________________________________ ERROR collecting test/test_googlecloud_idmaintainer.py _________________________________________________
ImportError while importing test module '/home/planetdyna/test/test_googlecloud_idmaintainer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/test_googlecloud_idmaintainer.py:4: in <module>
    from mockfirestore import MockFirestore
E   ImportError: No module named mockfirestore
_________________________________________________________ ERROR collecting test/test_hunter.py __________________________________________________________
ImportError while importing test module '/home/planetdyna/test/test_hunter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/test_hunter.py:2: in <module>
    import yaml
E   ImportError: No module named yaml
______________________________________________________ ERROR collecting test/test_id_maintainer.py ______________________________________________________
ImportError while importing test module '/home/planetdyna/test/test_id_maintainer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/test_id_maintainer.py:5: in <module>
    from flathunter.idmaintainer import IdMaintainer
E   ImportError: No module named flathunter.idmaintainer
________________________________________________________ ERROR collecting test/test_processor.py ________________________________________________________
ImportError while importing test module '/home/planetdyna/test/test_processor.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/test_processor.py:2: in <module>
    import yaml
E   ImportError: No module named yaml
_____________________________________________________ ERROR collecting test/test_sender_telegram.py _____________________________________________________
ImportError while importing test module '/home/planetdyna/test/test_sender_telegram.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/test_sender_telegram.py:1: in <module>
    import requests_mock
E   ImportError: No module named requests_mock
_____________________________________________________ ERROR collecting test/test_statistics_view.py _____________________________________________________
ImportError while importing test module '/home/planetdyna/test/test_statistics_view.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/test_statistics_view.py:3: in <module>
    import yaml
E   ImportError: No module named yaml
______________________________________________________ ERROR collecting test/test_web_interface.py ______________________________________________________
ImportError while importing test module '/home/planetdyna/test/test_web_interface.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/test_web_interface.py:3: in <module>
    import yaml
E   ImportError: No module named yaml
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 13 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by PlanetDyna** [comment]
I just deleted the "test" directory. Now the test is running, but no output:


============================================================================ test session starts =============================================================================
platform linux2 -- Python 2.7.17, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/planetdyna, inifile:
collected 0 items

**Comment by codders** [comment]
Hi @PlanetDyna ,

To be able to run the test suite, you will need to do a 'pip install -e .' from the project directory first.

If you still have trouble after that, let me know. Also please note that running the test suite multiple times will quite quickly get your IP blocked by the ebaykleinanzeigen servers, so expect those tests to start failing after a short while. But you can run any specific test with `pytest test/<whatever>.py`.

**Comment by PlanetDyna** [comment]
Sorry, codders. Dont know exactly what to do. I can open a remote session to show you the current situation. But where can I contact you?

**Comment by codders** [comment]
Sure. I'll get in touch - off to a meeting now but I'll be around later today / tomorrow morning.

**Comment by codders** [comment]
Can you e-mail me your Telegram UserID? arthur.taylor@gmail.com

**Comment by PlanetDyna** [comment]
I get it working. But for some eBay-URLs I got an error:

Traceback (most recent call last):
  File "/home/planetdyna/flathunter/flathunt.py", line 89, in <module>
    main()
  File "/home/planetdyna/flathunter/flathunt.py", line 86, in main
    launch_flat_hunt(config)
  File "/home/planetdyna/flathunter/flathunt.py", line 46, in launch_flat_hunt
    hunter.hunt_flats()
  File "/home/planetdyna/flathunter/flathunter/hunter.py", line 42, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/home/planetdyna/flathunter/flathunter/hunter.py", line 22, in crawl_for_exposes
    for searcher in self.config.searchers()
  File "/home/planetdyna/flathunter/flathunter/hunter.py", line 23, in <listcomp>
    for url in self.config.get('urls', list())])
  File "/home/planetdyna/flathunter/flathunter/abstract_crawler.py", line 48, in crawl
    return self.get_results(url, max_pages)
  File "/home/planetdyna/flathunter/flathunter/abstract_crawler.py", line 39, in get_results
    entries = self.extract_data(soup)
  File "/home/planetdyna/flathunter/flathunter/crawl_ebaykleinanzeigen.py", line 81, in extract_data
    rooms = re.match(r'(\d+)', tags[1].text)[1]
TypeError: 'NoneType' object is not subscriptable

**Comment by codders** [comment]
This URL fails: 

https://www.ebay-kleinanzeigen.de/s-41352/nachmieter/k0l1188r30
