### ISSUE TITLE
WebHunter is no longer sending expose messages to receiver_ids

### ISSUE THREAD

**Issue by codders** [flathunters/flathunter#35]
WebHunter doesn't send messages to users listed in receiver_ids who don't have settings stored in Firestore

**Comment by adlaube** [comment]
Dirty fix is to send messages before iterating over (the non existing) settings in firestore:

web_hunter.py : hunt_flats(...):

        processor_chain = ProcessorChain.builder(self.config) \
                                        .apply_filter(filter_set) \
                                        .crawl_expose_details() \
                                        .save_all_exposes(self.id_watch) \
                                        .resolve_addresses() \
                                        .calculate_durations() \
                                        .send_telegram_messages() \    #need to be added
                                        .build()

**Comment by codders** [comment]
Actually I think it's a pretty good fix - this should work! Thanks for the suggestion.

**Comment by codders** [comment]
I merged a PR with those changes. Considering this closed.
