### ISSUE TITLE
Codecov disappeared in PyPI -> pipenv install install isn't possible

### ISSUE THREAD

**Issue by mrclrchtr** [flathunters/flathunter#365]
Hi,

this is more for information to save others time. I searched for a while.

Codecov is no longer available in  PyPI. Because of that, `pipenv install` install isn't possible anymore:

`CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement codecov (from versions: none)`

Issue in codecov repo: https://github.com/codecov/python-standard/issues/31

It's possible to remove `codecov` from the `Pipfile` as workaround.

If I am correct codecov is required in the github actions? Maybe this repo can move to [codecov/codecov-action@v3](https://github.com/marketplace/actions/codecov)?

**Comment by yanone** [comment]
FWIW, I was just able to install by removing `codecov` from both relevant `pipenv` files.

**Comment by codders** [comment]
Thanks for the report! I'll take a look - moving over to the codecov action looks like a solid plan. Will try to take care of that this weekend.

**Comment by codders** [comment]
Should have been fixed in #367. Thanks for the report!
