### ISSUE TITLE
User question: self-hosting vs flathunter.codders.io

### ISSUE THREAD

**Issue by yanone** [flathunters/flathunter#366]
What are the differences of the Berlin hosted version vs. self-hosting, especially in terms of speed? There is no way to know the time lag of the hosted version, so I wanted to ask for your experience.

Also, how often will the ImmoScout24 cookie have to be overridden in practice? What is "a short period of time" here?

**Comment by codders** [comment]
Hi @yanone,

The Berlin hosted version is polling every 10 minutes. There isn't any significant delay vs. the self-hosted version.

I haven't personally tried with the Immoscout cookie - I don't know how long that's good for. But I would be interested in experience reports.

**Comment by yanone** [comment]
Thanks
