### ISSUE TITLE
a config.yaml example

### ISSUE THREAD

**Issue by bakikocabasa** [flathunters/flathunter#368]
Dear Developers, 

can you please give me an full example of config.yaml? I am having issues

**Comment by codders** [comment]
Hi @bakikocabasa ,

The repository includes `config.yaml.dist` which should give you an idea what a working config looks like. You can also use the `config_wizard.py` script to interactively create a valid configuration file.

**Comment by codders** [comment]
Hi @bakikocabasa ,

Did this work for you? Can we close this issue?

**Comment by bakikocabasa** [comment]
Yes, please.

Thank you!
