### ISSUE TITLE
Unable to run it on Google Cloud Run: AttributeError: 'Namespace' object has no attribute 'flathunter_config'

### ISSUE THREAD

**Issue by Mohamed3on** [flathunters/flathunter#373]
Hey! Thanks for your great work here :)

I'm trying to upload the project to Google Cloud Run. I'm using `config.yaml` for configuration. I uploaded the image via `gcloud builds submit --region=europe-west1` after changing the project ID in `cloudbuild.yaml`.

Unfortunately, when I try to execute this job on the GCloud, I get this error:

```
2023-04-27 09:34:10.961 CEST
AttributeError: 'Namespace' object has no attribute 'flathunter_config'
2023-04-27 09:34:27.761 CEST
Traceback (most recent call last): File "/usr/src/app/cloud_job.py", line 12, in <module> config_handle = args.flathunter_config
```

my hunch is that the config.yaml file is just not being uploaded correctly or at all. Is that true? And if so, how should I include the config in the image?

Thank you!

**Comment by codders** [comment]
Thanks for spotting this - I think this changed recently. Your pull request is very welcome :)
