### ISSUE TITLE
Ebay kleinanzeigen links not recognized

### ISSUE THREAD

**Issue by Bloxxxi** [flathunters/flathunter#383]
Ebay kleinanzeigen links stopped working for me although it worked a week ago.
Example link: https://www.kleinanzeigen.de/s-wohnung-mieten/muenchen/preis::1200/c203l6411r30
Output: URL did not match any configured scraper

**Comment by Bloxxxi** [comment]
Furthermore, ebay kleinanzeigen will update its website soon in May. The current links may be broken because it's their transition towards the new website.

**Comment by Bloxxxi** [comment]
The links are broken because www.ebay-kleinanzeigen.de got changed to www.kleinanzeigen.de

**Comment by codders** [comment]
Thanks for the report! I'll take a look.
