### ISSUE TITLE
Google cloud deployment failing

### ISSUE THREAD

**Issue by IhsenBouallegue** [flathunters/flathunter#440]
I get the following error when running `gcloud app deploy` and I am confused because I already setted it up in google cloud and game myself all the permissions. Is there something I am missing?
```
ERROR: (gcloud.app.deploy) Permissions error fetching application [apps/flathunters]. Please make sure that you have permission to view applications on the project and that ...@gmail.com has the App Engine Deployer (roles/appengine.deployer) role.
```

**Comment by IhsenBouallegue** [comment]
A reply would be really lovely. Leaving my laptop open 24/7 is not really ideal. I tried running it on a raspberry pi. Didn't work either.

**Comment by codders** [comment]
Hi @IhsenBouallegue ,

Sorry for the delay on the unpaid support of your free software...

Besides what Google offers you there:

```
Please make sure that you have permission to view applications on the project and that ...@gmail.com has the App Engine Deployer (roles/appengine.deployer) role.
```

I don't have a lot of suggestions. I guess you already did the steps `gcloud init` and `gcloud config set project flathunters` - when you logged into the SDK, you will need to have used a Google Account that has permissions to deploy to App Engine. You can always try deleting the gcloud config (`~/.config/gcloud`) and starting over - I don't know if that will help you.

**Comment by IhsenBouallegue** [comment]
Please excuse my frustration, searching for a place in Germany can be quite stressful.
Thank you for the reply though. I really appreciate it.
