### ISSUE TITLE
Bot keeps spamming "Spotahome" (paid) offers

### ISSUE THREAD

**Issue by tuschla** [flathunters/flathunter#450]
I have a bot instance running for WG gesucht for Berlin which is now mostly spamming the paid offers. I suspect they changed something with with the website Layout. Is there some option to ignore these companies altogether?

**Comment by codders** [comment]
Are you using the hosted version? Or running locally?

**Comment by codders** [comment]
Okay. If you can share me your search URL I can try and reproduce the
issue. It should be possible to add an exclude filter to your config file,
but maybe we also need to update the crawler.

Thanks!

tuschla ***@***.***> schrieb am Mi., 23. Aug. 2023, 19:32:

**Comment by tuschla** [comment]
Sure! Thanks a lot.
```
https://www.wg-gesucht.de/wg-zimmer-und-1-zimmer-wohnungen-und-wohnungen-in-Berlin.8.0+1+2.1.0.html?offer_filter=1&city_id=8&noDeact=1&dFr=1692784800&dTo=1698750000&radLat=52.5143951&radLng=13.3501359&sMin=16&rMax=750&radAdd=Gro%C3%9Fer%20Stern%201,%20Berlin,%20Deutschland,%2010557&radDis=5000&wgSea=2&wgAge=22&exc=2&categories[]=0&categories[]=1&categories[]=2&rent_types[]=0&user_filter_id=9030060
```

**Comment by codders** [comment]
Hi again,

I made a change which I think should filter out those results in PR #451. You can go ahead and try it, and please close this issue if it resolves your problem.

Thanks!

**Comment by tuschla** [comment]
I pulled and didn't receive any of the "official" listings so far. Thanks!
