### ISSUE TITLE
Hosted website only shows results from immoscout and wg-gesucht 

### ISSUE THREAD

**Issue by Melaniapopania** [flathunters/flathunter#452]
Hi, I noticed that the website and the bot stopped sending me results from kleinanzeigen since August 22. Could you maybe take a look on that? :) thanks!

**Comment by codders** [comment]
Hi @Melaniapopania,

Thanks for the report - that should be back in action now. Please recheck and close this ticket if it's working for you.

**Comment by Melaniapopania** [comment]
It’s working again! Thanks for the quick fix!!

**Comment by Melaniapopania** [comment]
It’s working again! Thanks for the quick fix!!
