### ISSUE TITLE
Immowelt Failing

### ISSUE THREAD

**Issue by mateen7861** [flathunters/flathunter#464]
Immowelt script is failing and crashing the complete script.

**Comment by codders** [comment]
Hi Mateen,

Can you be more specific? What error message is it crashing out with? What
Immowelt URL are you using?

Thanks!

Mateen Mustafa ***@***.***> schrieb am Di., 5. Sept. 2023,
12:08:

**Comment by codders** [comment]
Hi @mateen7861 ,

Without more information, I will close this ticket in a couple of days.
