### ISSUE TITLE
Unable to determine Chrome version on Windows

### ISSUE THREAD

**Issue by colinemonds** [flathunters/flathunter#465]
Hi,

flathunter is unable to determine the version of Chrome on Windows because
a) Chrome isn't usually in the PATH on Windows and 
b) flathunter tries to get the Chrome version by running it with --version, but Chrome does not respond to this flag on Windows.

PR incoming.

**Comment by colinemonds** [comment]
PR:
https://github.com/flathunters/flathunter/pull/466

**Comment by codders** [comment]
Hey! Thanks so much for the feature request and PR. I honestly had no idea we supported Windows :smile:

**Comment by colinemonds** [comment]
Aaaand tests are failing. I'll fix this later (if you're interested, it's fine as it is for my purposes :) ).

**Comment by codders** [comment]
Yeah - I think `pyright` is fine with `list` as a type, but the runtime wants `List`. If you get round to it later that's great. If not, I might patch it up tomorrow and merge it in.

Thanks again!
