### ISSUE TITLE
WG Gesucht returns more results than shown in browser

### ISSUE THREAD

**Issue by Hahny** [flathunters/flathunter#47]
The results of WG Gesucht differ from the entities shown in the browser. The URL structure from beautiful soup is also different from the one shown in the browser.

**Comment by codders** [comment]
Can you give an example of which URL you are using and what the difference is - what do you get vs. what do you expect?

**Comment by fkalbe** [comment]
I can confirm the issue that filters applied in the browser are not applied by the crawler. But I think this is a more general issue with WG-Gesucht.

To reproduce, search for flats in Berlin on WG-Gesucht and apply a filter to only show results in the quarter 'Kreuzberg'. I ended up with the following URL:

https://www.wg-gesucht.de/1-zimmer-wohnungen-in-Berlin.8.1.1.0.html?offer_filter=1&city_id=8&noDeact=1&categories%5B%5D=1&rent_types%5B%5D=0&ot%5B%5D=151

After playing around a bit, the final parameter (151 in this case) seems to be used to filter the quarter. However, when you open the same URL in a private browser session, the filtering is somehow gone (results other than Kreuzberg are included). Maybe cookies are involved?
