### ISSUE TITLE
Hacktoberfest?

### ISSUE THREAD

**Issue by veldhaenchen** [flathunters/flathunter#490]
I thought about adding the project to [Hacktoberfest](https://github.com/topics/hacktoberfest) to gain more traction?
@codders what do you think?

**Comment by codders** [comment]
Sounds good - can't hurt. What do we need to do?

Johannes Velde ***@***.***> schrieb am Mi., 4. Okt. 2023,
08:24:

**Comment by veldhaenchen** [comment]
you just need to add the label `hacktoberfest` to the project like [freeCodeCamp](https://github.com/freeCodeCamp/freeCodeCamp). After this it should appear in the topics as mentioned above.

**Comment by codders** [comment]
Going to close this because we added the label to the project.
