### ISSUE TITLE
ChromeNotFound when trying to crawl Immo

### ISSUE THREAD

**Issue by robertszooba** [flathunters/flathunter#501]
Hi,

I want to crawl Immo but after executing `python3 flathunt.py`, I received the following error:
```
File "/flathunter/flathunter/chrome_wrapper.py", line 53, in get_chrome_version
    raise ChromeNotFound()
flathunter.exceptions.ChromeNotFound
```
I was using flathunter three months ago, and it did work back then. The only thing that has changed, at least on my side, is an update to Sonoma.

I've seen that there was an issue related to this problem, but apparently it was solved by installing chrome. I'm using chroma on a daily basis, so I'm looking for another solution.

**Comment by codders** [comment]
Yeah - the other issue was #495. If you're seeing ChromeNotFound, it's really usually because the Chrome binary isn't in your path. You can try running `google-chrome --version` or `chromium --version` or `chrome --version` from the terminal where you run python. If all of those fail, it can't find the version of Chrome that it's supposed to use.

**Comment by robertszooba** [comment]
Do you know how to add Chrome to path?
First I tried with:
```
sudo ln -s /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome /usr/local/bin/google-chrome
```
But I kept receiving error messages. So I tried with `--headless`, i.e. made a script called `/usr/local/bin/google-chrome` and put the following there:
```
#!/bin/bash
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome "$@" --headless
``` 
But I'm getting:
`ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.`

Made a bit of googling, found a solution with `--disable-gpu` but it still does not work.

**Comment by codders** [comment]
I'm afraid you'll need to wait for someone with a Mac to reply. I'm running on Linux, so that's nothing I can test or reproduce.

**Comment by robertszooba** [comment]
If I understand correctly, we just want to get the major version of the installed Chrome. According to your knowledge about the program, is there anything that prevents simply returning `["118"]` from function `get_command_output`?

**Comment by codders** [comment]
Yeah - undetected_chromedriver is also going to need to be able to find Chrome, though if might have a different technique for doing that.

You can hard-code the version number, but then you just need to be aware that you'll have to change that code every time the chrome version changes (which is roughly every couple of months). The code is there to support flathunter working smoothly over a longer period of time.

**Comment by robertszooba** [comment]
Ok, resolved by creating a script (as above), but without the `--headless` option.

**Comment by noahskelton** [comment]
@robertszooba Got a solution I can use? I'm running into the same problem on MacOS

**Comment by friedrichtroescher** [comment]
I am running into the same issue. @robertszooba, can you share your solution?
