### ISSUE TITLE
ChromeNotFound when crawling Immobilienscout24 on MacOS

### ISSUE THREAD

**Issue by friedrichtroescher** [flathunters/flathunter#508]
This is pretty much the same issue as #501, I commented there but am creating this issue to raise a bit of awareness.

 @robertszooba seems to have fixed this, however I had no luck with his solution as seen below:

I tried using 

> sudo ln -s /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome /usr/local/bin/google-chrome

as robertszooba did in without success - it still produces this error:

> sudo pipenv run python flathunt.py
> [...]
> [2023/11/05 02:17:08|chrome_wrapper.py |INFO ]: Initializing Chrome WebDriver for crawler...
> [...]
> flathunter.exceptions.ChromeNotFound

Then, trying to create the script manually (again, as robertszooba did in #501) makes flathunter produce this error:

> sudo pipenv run python flathunt.py
> [...]
> [2023/11/05 02:11:46|chrome_wrapper.py |INFO ]: Initializing Chrome WebDriver for crawler...
> Traceback (most recent call last):
> [...]
> PermissionError: [Errno 13] Permission denied: 'google-chrome'

okay, so I set the permissions with

> chmod 755 /usr/local/bin/google-chrome

now, depending on wether I include the --headless in the script, I either get

> if headless or options.headless:
> AttributeError: 'ChromeOptions' object has no attribute 'headless'

or the original flathunter.exceptions.ChromeNotFound error.

Does anyone have any insight on this?

edit - formating

**Comment by adobryn** [comment]
Had the same issue, adjusted a script a bit:

chrome_wrapper.py
```
def get_chrome_driver(driver_arguments):
    """Configure Chrome WebDriver"""
    logger.info('Initializing Chrome WebDriver for crawler...')
    chrome_options = uc.ChromeOptions() # pylint: disable=no-member
    **chrome_options.add_argument("--headless")**
```

And also I had issues with finding chrome (maybe because of brew) so I've hardcoded a bit:
```
version_output = get_command_output(
            ['/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', '--version']
        )
```

**Comment by friedrichtroescher** [comment]
Thanks a lot @adobryn ! This works for me. I hope someone else can create a PR for this as I don't consider myself experienced enough. That path was the standard for me as well.
