### ISSUE TITLE
kleinanzeige vorübergehen gesperrt

### ISSUE THREAD

**Issue by czrty** [flathunters/flathunter#510]
Hi everyone, 
it is great work, thank you.
i made a mistake and used it in two different folders with different urls, both filters (urls) are for kleinanzeige. Since two program runs simultaneously, although time limit was 600, it called website more often than this....

I got the feedback, IP area is temporary blocked. Problem is, although i changed the IP( used my phone as hotspot got different IP), it keeps blocking. I am not IT expert, but, can we assume that, website doesnt block the IP-Bereich but the some parameters crawler has; header, fingerprinting or  some other informations? If this is the case, how can it be fixed?
Thank you.

**Comment by codders** [comment]
Hi @czrty ,

Thanks for your comment and the issue. I don't know exactly how the blocking works. We're using the `requests-random-user-agent` library to change the user agent for each request, and if you're changing your IP address then the only common elements are the request headers and of course the URL. You could experiment to see if a different search URL gets around the blocking, or you could check to see if you can access the page normally in your web browser.

**Comment by codders** [comment]
Okay. Then it might be time to switch Kleinanzeigen over to use the headless browser that we have for Immoscout. That should make it much harder to detect.

**Comment by czrty** [comment]
it is still blocked :)

**Comment by codders** [comment]
But on the bright side, still accepting pull requests!

czrty ***@***.***> schrieb am Mo., 4. Dez. 2023, 22:25:

**Comment by czrty** [comment]
do you know, is it planned to make changes in kleinanzeige.py?

**Comment by czrty** [comment]
i would like too, i learnt python for it:) i tried to look at immobilienscout and update kleinanzeige. it was still blocked.
as i mentioned, all is new to me, python, crawler.

**Comment by czrty** [comment]
i looked scout code and fitted the kleinanzeige. it is not blocked anymore. I also got links, but after a while, program exited with the following error;
 crawler/kleinanzeigen.py", line 85, in extract_data
    price = expose_ids[idx].find(
IndexError: list index out of range

have you got tips for it? it is clear to me why it happens, but not clear to me how to fix it. i have zero knowledge about html or code of web pages:)

**Comment by czrty** [comment]
is it still recommended to have 600 seconds  wait time for kleinanzeige, iif t uses headless browser like scout?

**Comment by codders** [comment]
That's hard to say. If they have changed their bot detection, we won't know
what the new rules are until we try them. If you're not worried about being
blocked for a couple of days, you could reduce the time and see what
happens.

Do you have code that's ready for review? Do you want to push your branch
up to your fork and make a pull request so that I can take a look?

Thanks,

Arthur

czrty ***@***.***> schrieb am So., 10. Dez. 2023, 09:54:

**Comment by czrty** [comment]
Hi Artur, 
i will not take the risk, they dont block only for few days but permanently :) 

i ljust earnt python last week  to see if i can make update the code, i fitted it like on the scout but, i am not sure if it is good code to merge.

**Comment by codders** [comment]
Hey @czrty ,

I see you closed this ticket - can you share your modified code?

**Comment by codders** [comment]
Merged in #511 from @Dimfred. This seems to fix the issue. I've deployed an updated image to the hosted flathunter instance. Thanks @Dimfred!
