### ISSUE TITLE
not receiving any listings from Immoscout24

### ISSUE THREAD

**Issue by tomasmena** [flathunters/flathunter#513]
Currently the bot is not sendig listings from Immoscout24

**Comment by MichelFR** [comment]
After the PR its still not working on my side.
Added a fresh token.

![image](https://github.com/flathunters/flathunter/assets/7061122/f437c419-cc8b-48f8-8fa8-a21daae1544c)

**Comment by codders** [comment]
I redeployed the latest code, and Immoscout listings seem to be back. Can you confirm?

**Comment by tomasmena** [comment]
Yes! There back. Thanks

**Comment by codders** [comment]
No probs. Thanks for the report!

**Comment by codders** [comment]
This is hopefully now implemented with #634 . Comment / re-open the ticket if you're still having issues.
