### ISSUE TITLE
Replace Google Chrome with Chromium in Dockerfile

### ISSUE THREAD

**Issue by Alexandero89** [flathunters/flathunter#533]
Hey all,

is there a special reason Google Chrome is used in the Dockerfile instead of Chromium? ( [see here](https://github.com/flathunters/flathunter/blob/73a6229a8d0695b8c1c938022a70a0ede57e3921/Dockerfile#L9) )
Maybe because of detection reasons or something?
Otherwise i would create a PR to replace the proprietary Google Chrome with Chromium (which has almost the same features, but no tracking and google stuff).

I think @alexanderroidl implemented this and could maybe say something?

**Comment by codders** [comment]
From my side no particular reason. I would be happy to switch to Chromium - I haven't had any reports that Chromium works worse than Chrome. We could even see if Firefox does what we need - it's never been a better time to switch to Firefox.

**Comment by Alexandero89** [comment]
Good point.
Will also check if Firefox will be able to replace Chrome.

I hope the tests are good enough to catch all errors, because i think i dont know the tool good enough to see all the edge cases where this swap could fail or produce errors.

**Comment by codders** [comment]
Awesome - thank you! The test coverage is pretty good, except that the selenium integration tests don't run for PRs because of permissions issues. So if the tests pass for you locally and crawling immoscout with Firefox works, then we can try it and see if the tests still pass after merge.

**Comment by codders** [comment]
Ah. One thing. For Chrome we have undetected_chromedriver, which is important for bot detection. I don't know if there's something similar for Firefox

**Comment by Alexandero89** [comment]
As far as i see there is nothing like undetected-geckodriver ( see [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/629) )
I only found a preference to turn off ( [see](https://stackoverflow.com/questions/58873022/how-can-i-make-a-selenium-script-undetectable-using-geckodriver-and-firefox-thro)) but i dont know if this would be enough and would reach the same scope of undetected_chromedriver.

So for now i would just replace chrome with chromium and do some research before later on maybe replace it to firefox.
