### ISSUE TITLE
Add a heartbeat message, to ensure the software is running

### ISSUE THREAD

**Issue by Shoggomo** [flathunters/flathunter#58]
This is good for debugging and making sure the program is still running, which otherwise cannot be known without chechink it manually. This can be tedious, when the program is running on a server and supposed to be a set and forget type thing.

So a feature, that a "I'm still alive" message is sent regularly (maybe once a day or week, this should be configurable) may make sense.

**Comment by step21** [comment]
I would suggest using sth like supervisor + cronitor or healthchecks.io. Much easier than building it in.

**Comment by Manuel030** [comment]
see related PR #159

**Comment by codders** [comment]
#159 is merged now - this issue is resolved.
