### ISSUE TITLE
Bot domain invalid

### ISSUE THREAD

**Issue by tomsegal89** [flathunters/flathunter#585]
First of all THANK YOU for this awesome product :) 
the telegram link here [removed] doesn't work/appear, inside "Bot domain invalid" is displayed.

Thanks!

**Comment by codders** [comment]
Should be flathunter.codders.de - had to move it because of the Chagossians.

Where do you see the old link?

Thanks,

Arthur

Tom Segal ***@***.***> schrieb am Do., 9. Mai 2024, 16:11:

**Comment by tomsegal89** [comment]
here https://flathunter.codders.io/

thanks for the fast reply :)
_______________
www.tomsegal.com


Am Do., 9. Mai 2024 um 16:47 Uhr schrieb Arthur Taylor <
***@***.***>:

**Comment by codders** [comment]
No, I mean, I know the site exists :) How did you get directed to the codders.io domain instead of the codders.de? Is the old domain still in a document somewhere? Or did you find it on the web?

**Comment by tomsegal89** [comment]
i have the link saved but i think it also shows up in google
_______________
www.tomsegal.com


Am Do., 9. Mai 2024 um 18:10 Uhr schrieb Arthur Taylor <
***@***.***>:

**Comment by codders** [comment]
Okay. I've edited a previous comment of mine to direct to https://flathunter.codders.de . Would be great if you could change the comments you have made here so that the .io site loses the rest of its google juice.
