### ISSUE TITLE
`Config file loaction must be specified` after having pulled commits made after 29.04.24

### ISSUE THREAD

**Issue by robertszooba** [flathunters/flathunter#588]
Despite unstable operation and frequent crashes due to various errors (`IS24 bot detection`, `undetected_chromedriver`) I had managed to run the program until now. Unfortunately, after executing the pull command, which updated my version with commits made after 29/04/24, I am unable to start the program at all due to the following error: `flathunter.exceptions.ConfigException: Config file loaction must be specified, or FLATHUNTER_TARGET_URLS must be set`.
Has anything changed in the way the configuration file (`config.yaml`) is processed?

**Comment by codders** [comment]
Hey hey,

Yeah - I changed the config parsing yesterday. The tests passed, but I
didn't try running the app manually. Can you roll back to the previous
version and check that that fixes your issue?

Thanks

robertszooba ***@***.***> schrieb am Sa., 11. Mai 2024, 11:41:

**Comment by robertszooba** [comment]
Reverting to the newest commit (as of 11/5) to the one with the message name `Fix quoting issue in config dis` (9/5) solves the issue.

**Comment by codders** [comment]
I made a change in #591 that should resolve the issue you saw
