### ISSUE TITLE
Immowelt is limited to first 4 entries of result list

### ISSUE THREAD

**Issue by Benedikt1992** [flathunters/flathunter#60]
The crawler of immowelt will only search for matching flats in the first 4 entries of the result list. 

All further results are loaded asynchronously on immowelt. The crawler does not load these entries. Usually they would be located in a `<div id="listItemWrapperAsync" ... >` after loading.

**Comment by codders** [comment]
Yep. This is a real thing. With the latest changes from @xMordax , we will have Selenium / Chrome Webdriver support in the project, which would make it possible to load those dynamic elements. Maybe you can try again once that's merged.
