### ISSUE TITLE
The "Blacklist" parameter does not seem to work.

### ISSUE THREAD

**Issue by mrRo8o7** [flathunters/flathunter#614]
I have the flathunter bot running. It also regularly sends me new search results. However, the "blacklist" parameter from _config.yaml_ does not seem to work. I get search results from wg-gesucht.de and kleinanzeigen.de from districts that are on the blacklist.

**Comment by codders** [comment]
Oof. Yeah. Sorry about that. It looks like it must have been there in connection with the distance calculations feature, which I'm not sure anyone is using. But that feature has been disabled for a while. I've removed the reference to the feature in the config file in #655 . You might have some luck with the `exclude_titles` config, which is wired up to actual functionality. But that doesn't filter the addresses themselves.
