### ISSUE TITLE
FYI Code of Conducts (CoCs) are missing your mail adress and differ between German and English

### ISSUE THREAD

**Issue by rugk** [flathunters/flathunter#636]
https://github.com/flathunters/flathunter/blob/main/CODE_OF_CONDUCT.en.md and the German version not only differ (the English version seems to be more elaborate maybe as it's based on the newer v2.0 template instead of 1.4), but more importantly also _both_ miss your contact method/mail. As such, this renders them pretty much unactionable, does not it?

The template needs to be filled in you know… :wink:

**Comment by codders** [comment]
My bad - fixed that now!
