### ISSUE TITLE
Add Hacktoberfest tag

### ISSUE THREAD

**Issue by IAL32** [flathunters/flathunter#76]
It would be nice if the 3 PR that I made counted towards the goal for my shirt (never got one, and this year 
the rules are very strict)

Henceforth, I think it would be nice if the repository added the tag.

https://youtu.be/FxBv4FMcDgo

The link above shows how.

If you are not familiar with what Hacktoberfest is, you can check out a description here: https://hacktoberfest.digitalocean.com/

Thanks for the consideration!

**Comment by codders** [comment]
Sounds cool - I'll look at that this week :)

**Comment by codders** [comment]
Done - enjoy your t-shirt!
