### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text' in crawl_wggesucht

### ISSUE THREAD

**Issue by fkalbe** [flathunters/flathunter#79]
I recently noticed that the crawler crashes on WG-Gesucht with the following error:

```python

Traceback (most recent call last):

  File "C:\Users\X\Documents\Python\flathunter\flathunt.py", line 89, in <module>
    main()

  File "C:\Users\X\Documents\Python\flathunter\flathunt.py", line 86, in main
    launch_flat_hunt(config)

  File "C:\Users\X\Documents\Python\flathunter\flathunt.py", line 46, in launch_flat_hunt
    hunter.hunt_flats()

  File "C:\Users\X\Documents\Python\flathunter\flathunter\hunter.py", line 42, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):

  File "C:\Users\X\Documents\Python\flathunter\flathunter\default_processors.py", line 30, in process_expose
    expose['address'] = searcher.load_address(url)

  File "C:\Users\X\Documents\Python\flathunter\flathunter\crawl_wggesucht.py", line 81, in load_address
    .find("a", {"href": "#"}).text.strip().split())

AttributeError: 'NoneType' object has no attribute 'text'

```

This part in the `load_address()` method in `crawl_wggesucht.py` causes the error:

```python
        address = ' '.join(response.find('div', {"class": "col-sm-4 mb10"})
                           .find("a", {"href": "#"}).text.strip().split())
```

I think the problem is the `.find("a", {"href": "#"})` part returns a NoneType reflecting that nothing was found. Maybe the implementation on WG-Gesucht has changed slightly? To me it looks like the href is now "#mapContainer". So if I change the problematic line to

```python
        address = ' '.join(response.find('div', {"class": "col-sm-4 mb10"})
                           .find("a", {"href": "#mapContainer"}).text.strip().split())
```

things seem to work fine again. Can anyone confirm this?

**Comment by codders** [comment]
Hey @fkalbe,

Thanks for the report - it looks like that might be a good fix. Can you confirm which URL you are crawling, so that I can test here?

Arthur

**Comment by fkalbe** [comment]
Sure, I tried with:

https://www.wg-gesucht.de/1-zimmer-wohnungen-in-Berlin.8.1.1.0.html?offer_filter=1&city_id=8&noDeact=1&categories%5B%5D=1&rent_types%5B%5D=0&ot%5B%5D=151

**Comment by codders** [comment]
Yup. I confirm I see the same problem, and the change you proposed fixes things. Thanks for the hint!
