### ISSUE TITLE
418 You look like a robot  with Ebay Kleinanzeigen

### ISSUE THREAD

**Issue by rusagent** [flathunters/flathunter#87]
I get this message when using the chromedriver in conjunction with the 2captcha service. I even set the sleeping_time to 650.

` Got response (418): b'<!DOCTYPE html>\n<html>\n  <head>\n    <title>418 You look like a robot (1). If you think you are not, contact us: service@ebay-kleinanzeigen.de\\n \\n54.155.47.221</title>\n  </head>\n  <body>\n    <h1>Error 418 You look like a robot (1). If you think you are not, contact us: service@ebay-kleinanzeigen.de\\n \\n54.155.47.221</h1>\n    <p>You look like a robot (1). If you think you are not, contact us: service@ebay-kleinanzeigen.de\\n \\n54.155.47.221</p>\n    <h3>Guru Meditation:</h3>\n    <p>XID: 253749141</p>\n    <hr>\n    <p>Varnish cache server</p>\n  </body>\n</html>\n'`

**Comment by rusagent** [comment]
I actually still get this... 

Got response (418): b'<!DOCTYPE html>\n<html>\n  <head>\n    <title>418 You look like a robot (1). If you think you are not, contact us: service@ebay-kleinanzeigen.de\\n \\n54.217.157.65</title>\n  </head>\n  <body>\n    <h1>Error 418 You look like a robot (1). If you think you are not, contact us: service@ebay-kleinanzeigen.de\\n \\n54.217.157.65</h1>\n    <p>You look like a robot (1). If you think you are not, contact us: service@ebay-kleinanzeigen.de\\n \\n54.217.157.65</p>\n    <h3>Guru Meditation:</h3>\n    <p>XID: 221914025</p>\n    <hr>\n    <p>Varnish cache server</p>\n  </body>\n</html>\n'

**Comment by mordax777** [comment]
I might have some time next or the week after and will try to reproduce the error. Probably we will have to migrate it to Selenium.

**Comment by rusagent** [comment]
This is still an issue. Do you know when you have time to fix this?

**Comment by mordax7** [comment]
Cannot reproduce
