### ISSUE TITLE
Error from Telegram

### ISSUE THREAD

**Issue by rusagent** [flathunters/flathunter#88]
I get this error:
`
2020-10-21T04:52:04.525696+00:00 app[worker.1]: [[94m2020/10/21 04:52:04[0m|[94msender_telegram.py[0m|[93mERROR   [0m]: When sending bot message, we got status 429 with message: {'ok': False, 'error_code': 429, 'description': 'Too Many Requests: retry after 34', 'parameters': {'retry_after': 34}}
`
Is that normal?

**Comment by jossiamsee** [comment]
Too many Messages/ Receiver IDs? The Telegram FAQ may be helpful:

_My_ bot is hitting limits, how do I avoid this?
When sending messages inside a particular chat, avoid sending more than one message per second. We may allow short bursts that go over this limit, but eventually you'll begin receiving 429 errors.
If you're sending bulk notifications to multiple users, the API will not allow more than 30 messages per second or so. Consider spreading out notifications over large intervals of 8—12 hours for best results.
Also note that your bot will not be able to send more than 20 messages per minute to the same group.

**Comment by codders** [comment]
Yeah. I wonder a bit how many messages you're sending out. When flathunter first starts, it might find a lot of exposes by crawling a bunch of URLs, but it should remember which exposes it has already seen. After the first run, I wouldn't expect that you send more than a few messages per minute.

Either that or you have a lot of recipient IDs, but that's not very common either.
