### ISSUE TITLE
chromedriver on Google Cloud

### ISSUE THREAD

**Issue by sodiumstar** [flathunters/flathunter#96]
Hi,
Sorry for this trivial question, but I cannot get chromedriver to start in the Google Cloud. My latest guess for config.yaml was "driver_path: /usr/local/bin/chromedriver", because this is the path mentioned in the joyzoursky dockerfile.

On Google Cloud I get these messages:
- FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/chromedriver': '/usr/local/bin/chromedriver' 
- selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

As I'm not at all familiar with Google Cloud, I'm not sure how to find out where the executable is actually located.

Cheers
  Martin

**Comment by codders** [comment]
Hi Martin,

Are you trying to deploy this using `gcloud app deploy`? I don't think it is possible to use Selenium / headless Chrome in this environment. I have been investigating ways to support Selenium for the cloud deployments, but with the current code it isn't possible.

**Comment by sodiumstar** [comment]
Yes, I'm trying to use `gcloud app deploy` and I'm not trying to do anything special, just following what is described in the instructions. Does this mean the whole captcha recognition thing doesn't work with cloud deployments or how should the captcha section in config.yaml look like in this case?

**Comment by staffellauf** [comment]
Hi! Anything new on this Issue? I'm facing exactly the same problem plus I'm getting a `502 Bad Gateway nginx ` failure when trying to open the Web Interface.

**Comment by sodiumstar** [comment]
I'm also still waiting for an answer.

**Comment by codders** [comment]
The project has now been updated to support Google Cloud Run, which means we can use a docker container to run chromedriver. Please checkout the instructions in the README for Google Cloud Run.
