### ISSUE TITLE
Immoscout Stopped Working

### ISSUE THREAD

**Issue by Scribilicious** [flathunters/flathunter#97]
Immoscout stopped working. The crawler gets following message:

<div class="main_part2_header2">Warum haben wir deine Suchanfragen blockiert?</div>
<div class="main_part2_text2">Es kann verschiedene Gründe haben, warum wir dich fälschlicherweise als Roboter identifiziert haben. Möglicherweise</div>
</div>
<div class="main__list">
<ul>
<li>hast du die Cookies für unsere Seite deaktiviert.</li>
<li>hast du die Ausführung von JavaScript deaktiviert.</li>
<li>nutzt du ein Browser-Plugin eines Drittanbieters, beispielsweise einen Ad-Blocker.</li>

**Comment by flomllr** [comment]
I received the same message, but it still works if you have 2captcha.com configured (see config.yaml)

**Comment by codders** [comment]
Yup. You need 2captcha, because of the aggressive filtering at Immoscout.

**Comment by codders** [comment]
I added a note in the README to try and make this more clear.
